/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Administrator
 */
public class HeaderShift extends javax.swing.JPanel {

    
    public JLabel getLblSubTitle() {
        return lblSubTitle;
        
    }

    public void setLblSubTitle(JLabel lblSubTitle) {
        this.lblSubTitle = lblSubTitle;
    }

    public JLabel getLblTile() {
        return lblTile;
    }

    /**
     * Creates new form HeaderShift
     */
    public void setLblTile(JLabel lblTile) {    
        this.lblTile = lblTile;
    }

    public HeaderShift() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTile = new JLabel();
        lblSubTitle = new JLabel();

        setBackground(new Color(108, 165, 200));

        lblTile.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTile.setForeground(new Color(255, 255, 255));
        lblTile.setText("Quản lý nhân viên");

        lblSubTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblSubTitle.setForeground(new Color(204, 204, 204));
        lblSubTitle.setText("> Phân ca nhân viên");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubTitle)
                .addContainerGap(601, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSubTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
            .addComponent(lblTile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

  
    
    public void setTitle(String title){
        lblTile.setText(title);
    }
    
    public void setSubTitle(String subTitle){
        lblSubTitle.setText(subTitle);
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel lblSubTitle;
    private JLabel lblTile;
    // End of variables declaration//GEN-END:variables
}
