/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.modal;

import javax.swing.*;
import java.awt.*;

/**
 * @author THIS PC
 */
public class SendResetCodeModal extends JPanel {

    /**
     * Creates new form SendResetCodeModal
     */
    public SendResetCodeModal() {
        initComponents();
        btnLogin.setBorderPainted(false);     // Tắt vẽ viền
        btnLogin.setFocusPainted(false);      // Tắt viền focus (màu xanh khi click)
        btnLogin.setContentAreaFilled(false); // Không tô nền
        btnLogin.setOpaque(false);            // Trong suốt
        btnLogin.setForeground(new Color(33, 150, 243)); // Màu chữ xanh link
        btnLogin.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Con trỏ dạng tay
        btnLogin.setFont(new Font("Segoe UI", Font.PLAIN, 13));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new JLabel();
        lblMessage = new JLabel();
        lblEmail = new JLabel();
        lblName = new JLabel();
        lblPosition = new JLabel();
        avatarLabel1 = new iuh.fit.se.group1.ui.component.custom.AvatarLabel();
        btnSendCode = new iuh.fit.se.group1.ui.component.custom.Button();
        btnLogin = new JButton();
        jSeparator1 = new JSeparator();

        setBackground(new Color(255, 255, 255));

        lblTitle.setBackground(new Color(51, 51, 51));
        lblTitle.setFont(new Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new Color(51, 51, 51));
        lblTitle.setHorizontalAlignment(SwingConstants.CENTER);
        lblTitle.setText("Quên mật khẩu ?");

        lblMessage.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        lblMessage.setText("<html>Mật khẩu sẽ gửi về email của bạn <br/>vui lòng kiểm tra</html>");

        lblEmail.setForeground(new Color(51, 51, 51));
        lblEmail.setText("n****inh**@***");

        lblName.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        lblName.setForeground(new Color(102, 102, 102));
        lblName.setText("Nguyễn Trần Quốc Việt");

        lblPosition.setForeground(new Color(51, 51, 51));
        lblPosition.setHorizontalAlignment(SwingConstants.CENTER);
        lblPosition.setText("Nhân viên quản lí");

        GroupLayout avatarLabel1Layout = new GroupLayout(avatarLabel1);
        avatarLabel1.setLayout(avatarLabel1Layout);
        avatarLabel1Layout.setHorizontalGroup(
                avatarLabel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 60, Short.MAX_VALUE)
        );
        avatarLabel1Layout.setVerticalGroup(
                avatarLabel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 60, Short.MAX_VALUE)
        );

        btnSendCode.setBackground(new Color(91, 189, 84));
        btnSendCode.setForeground(new Color(255, 255, 255));
        btnSendCode.setText("Gửi lại mã");
        btnSendCode.setFont(new Font("Segoe UI", 1, 12)); // NOI18N

        btnLogin.setForeground(new Color(50, 145, 255));
        btnLogin.setText("Đăng nhập bằng mật khẩu");
        btnLogin.setBorder(BorderFactory.createLineBorder(new Color(255, 255, 255)));

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(lblTitle, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jSeparator1)
                                                .addContainerGap())
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblMessage, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                                .addComponent(avatarLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addGap(53, 53, 53))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(btnLogin, GroupLayout.PREFERRED_SIZE, 183, GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnSendCode, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE)
                                                                .addGap(14, 14, 14))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lblEmail, GroupLayout.PREFERRED_SIZE, 166, GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(lblPosition, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
                                                                .addGap(21, 21, 21))
                                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(lblName, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTitle)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblMessage, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(avatarLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblEmail)
                                        .addComponent(lblPosition))
                                .addGap(18, 18, 18)
                                .addComponent(lblName)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSendCode, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnLogin))
                                .addGap(11, 11, 11))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLblTitle() {
        return lblTitle;
    }

    public void setLblTitle(JLabel lblTitle) {
        this.lblTitle = lblTitle;
    }

    public JLabel getLblPosition() {
        return lblPosition;
    }

    public void setLblPosition(JLabel lblPosition) {
        this.lblPosition = lblPosition;
    }

    public JLabel getLblName() {
        return lblName;
    }

    public void setLblName(JLabel lblName) {
        this.lblName = lblName;
    }

    public JLabel getLblMessage() {
        return lblMessage;
    }

    public void setLblMessage(JLabel lblMessage) {
        this.lblMessage = lblMessage;
    }

    public JLabel getLblEmail() {
        return lblEmail;
    }

    public void setLblEmail(JLabel lblEmail) {
        this.lblEmail = lblEmail;
    }


    public void setTextEmail(String email) {
        lblEmail.setText(maskEmail(email));
    }

    public String maskEmail(String email) {
        if (email == null || !email.contains("@")) {
            return email;
        }

        String[] parts = email.split("@");
        String username = parts[0];
        String domain = parts[1];

        // Giữ 2 ký tự đầu phần username, phần còn lại thay bằng '*'
        String maskedUsername = username.length() <= 2
                ? username.charAt(0) + "*"
                : username.substring(0, 2) + "*".repeat(username.length() - 2);

        // Giữ 1 ký tự đầu domain + phần sau dấu chấm cuối
        int dotIndex = domain.lastIndexOf('.');
        String domainName = dotIndex > 0 ? domain.substring(0, dotIndex) : domain;
        String domainExt = dotIndex > 0 ? domain.substring(dotIndex) : "";

        String maskedDomain = domainName.length() <= 1
                ? domainName.charAt(0) + "*"
                : domainName.substring(0, 1) + "*".repeat(domainName.length() - 1);

        return maskedUsername + "@" + maskedDomain + domainExt;
    }

    public void goToBackLogin(java.awt.event.ActionListener evt) {
        btnLogin.addActionListener(evt);
    }

    public void sendResetCode(java.awt.event.ActionListener evt) {
        btnSendCode.addActionListener(evt);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private iuh.fit.se.group1.ui.component.custom.AvatarLabel avatarLabel1;
    private JButton btnLogin;
    private iuh.fit.se.group1.ui.component.custom.Button btnSendCode;
    private JSeparator jSeparator1;
    private JLabel lblEmail;
    private JLabel lblMessage;
    private JLabel lblName;
    private JLabel lblPosition;
    private JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
