/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.modal;

import iuh.fit.se.group1.ui.swing.TextField;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author THIS PC
 */
public class VerifyIdentityModal extends javax.swing.JPanel {

    /**
     * Creates new form VerifyIdentityModal
     */
    public VerifyIdentityModal() {
        initComponents();
        setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new iuh.fit.se.group1.ui.component.custom.Button();
        btnContinue = new iuh.fit.se.group1.ui.component.custom.Button();
        txtCitizenID = new TextField();
        lblTitle = new javax.swing.JLabel();

        setBackground(new Color(255, 255, 255));

        btnBack.setBackground(new Color(153, 153, 153));
        btnBack.setForeground(new Color(255, 255, 255));
        btnBack.setText("Quay lại");
        btnBack.setBorderRadius(25);
        btnBack.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnContinue.setBackground(new Color(91, 189, 64));
        btnContinue.setForeground(new Color(255, 255, 255));
        btnContinue.setText("Tiếp tục");
        btnContinue.setBorderRadius(25);
        btnContinue.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        btnContinue.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        txtCitizenID.setLabelText("Nhập căn cước công dân của bạn");
        txtCitizenID.setLineColor(new Color(102, 102, 102));
        txtCitizenID.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtCitizenIDActionPerformed(evt);
            }
        });

        lblTitle.setFont(new Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new Color(51, 51, 51));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Quên mật khẩu?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(txtCitizenID, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCitizenID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents


    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Tạo hình bo góc
        int arc = 30;
        Shape clip = new java.awt.geom.RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), arc, arc);
        g2.setClip(clip);

        // Vẽ nền
        g2.setColor(getBackground());
        g2.fillRect(0, 0, getWidth(), getHeight());

        super.paintComponent(g2);
        g2.dispose();
    }


    public TextField getTxtCitizenID() {
        return txtCitizenID;
    }

    public void setTxtCitizenID(TextField txtCitizenID) {
        this.txtCitizenID = txtCitizenID;
    }

    public void sendRestCode (ActionListener e){
        btnContinue.addActionListener(e);
    }
    
     public void closeModal (ActionListener e){
        btnBack.addActionListener(e);
    }
    
    private void txtCitizenIDActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txtCitizenIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCitizenIDActionPerformed

    private void btnContinueActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContinueActionPerformed

    private void btnBackActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private iuh.fit.se.group1.ui.component.custom.Button btnBack;
    private iuh.fit.se.group1.ui.component.custom.Button btnContinue;
    private javax.swing.JLabel lblTitle;
    private TextField txtCitizenID;
    // End of variables declaration//GEN-END:variables
}
