/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.table;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

/**
 * @author vietn
 */
public class Table extends JPanel {

    /**
     * Creates new form OrderTable
     */
    public Table() {
        initComponents();

        // Tạo event bên ngoài
        TableActionEvent event = new TableActionEvent() {
            @Override
            public void onEdit(int row) {
            }

            @Override
            public void onDelete(int row) {
                if (tbl.isEditing()) {
                    tbl.getCellEditor().stopCellEditing();
                }
                DefaultTableModel model = (DefaultTableModel) tbl.getModel();
                model.removeRow(row);
            }
        };

        setTableActionColumn(tbl, 4, event, false);

        tbl.getTableHeader().setPreferredSize(new Dimension(tbl.getTableHeader().getWidth(), 35));
        tbl.getTableHeader().setBackground(Color.decode("#B9B9B9"));
        tbl.setShowGrid(true);
        tbl.setGridColor(Color.LIGHT_GRAY); // màu đường kẻ ô
    }

    //    public void setTableActionColumn(JTable table, int columnIndex, TableActionEvent event, boolean isView ) {
//        table.getColumnModel().getColumn(columnIndex)
//                .setCellRenderer(new TableActionCellRender());
//        table.getColumnModel().getColumn(columnIndex)
//                .setCellEditor(new TableActionCellEditor(event));
//
//    }
    public void setTableActionColumn(JTable table, int columnIndex, TableActionEvent event, boolean isView) {
        table.getColumnModel().getColumn(columnIndex)
                .setCellRenderer(new TableActionCellRender(isView));
        table.getColumnModel().getColumn(columnIndex)
                .setCellEditor(new TableActionCellEditor(event, isView));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scr = new JScrollPane();
        tbl = new JTable();

        setBackground(new Color(241, 241, 241));

        scr.setBackground(new Color(255, 255, 255));

        tbl.setBackground(new Color(241, 241, 241));
        tbl.setModel(new DefaultTableModel(
                new Object[][]{
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null}
                },
                new String[]{
                        "Mã hoá đơn", "Họ tên khách", "Ngày tạo", "Số điện thoại", "Giá", "Loại phòng", "Chức năng"
                }
        ));
        tbl.setRowHeight(40);
        scr.setViewportView(tbl);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(scr, GroupLayout.DEFAULT_SIZE, 1034, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(scr, GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public JScrollPane getScr() {
        return scr;
    }

    public void setScr(JScrollPane scr) {
        this.scr = scr;
    }

    public void setBackGroundScr(Color c){
        scr.setBackground(c);
    }
    
    public JTable getTbl() {
        return tbl;
    }

    public void setTbl(JTable tbl) {
        this.tbl = tbl;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JScrollPane scr;
    private JTable tbl;
    // End of variables declaration//GEN-END:variables
}
