package iuh.fit.se.group1.network;

import java.io.Serializable;

public enum CommandType implements Serializable {
    AUTH_LOGIN,
    AUTH_LOGOUT,
    AUTH_RESET_PASSWORD,
    AUTH_VALIDATE_MANAGER,
    AUTH_CHANGE_PASSWORD,


    EMPLOYEE_GET_BY_ID,
    EMPLOYEE_GET_BY_ACCOUNT_ID,
    EMPLOYEE_GET_BY_CITIZEN,
    EMPLOYEE_GET_ALL,
    EMPLOYEE_GET_BY_KEYWORDS,
    EMPLOYEE_GET_BY_CITIZEN_ID,
    EMPLOYEE_GET_BY_ROLE_ID,
    EMPLOYEE_CREATE,
    EMPLOYEE_UPDATE,
    EMPLOYEE_DELETE,

    AMENITY_GET_BY_ID,
    AMENITY_GET_ALL,
    AMENITY_GET_BY_KEYWORDS,
    AMENITY_CREATE,
    AMENITY_UPDATE,
    AMENITY_DELETE,

    ORDER_GET_BY_ID,
    ORDER_GET_ALL,
    ORDER_GET_ALL_WITH_RELATIONSHIP,
    ORDER_GET_UNPAID,
    ORDER_GET_UNPAID_BY_KEYWORD,
    ORDER_SEARCH_BY_KEYWORD,
    ORDER_CREATE,
    ORDER_UPDATE_STATUS_PAID,
    ORDER_UPDATE_DEPOSIT,
    ORDER_DELETE,
    ORDER_GET_REVENUE_BETWEEN_DATES,
    ORDER_GET_REVENUE_BETWEEN_DATES_BY_ROOM_TYPE,
    ORDER_GET_REVENUE_BETWEEN_DATES_BOOKING_COUNT,
    ORDER_CREATE_RECORD,
    ORDER_UPDATE_TOTAL_PRICE,
    ORDER_MOVE_BOOKING_TO_ORDER,
    ORDER_RE_CALCULATE_TOTAL_PRICE,
    ORDER_UPDATE_ORDER_TYPE,
    ORDER_GET_ALL_WITH_RELATIONSHIP_COMPLETE_YET,
    ORDER_GET_UN_PENDING_BY_KEYWORD,

    ORDER_DETAIL_GET_BY_ID,
    ORDER_DETAIL_DELETE_BY_ID,
    ORDER_DETAIL_CREATE,
    ORDER_DETAIL_FROM_ORDER,
    ORDER_DETAIL_UPDATE_FROM_ORDER,

    BOOKING_GET_PRICE_FROM_BOOKING,

    CUSTOMER_GET_BY_ID,
    CUSTOMER_GET_ALL,
    CUSTOMER_GET_BY_KEYWORDS,
    CUSTOMER_CREATE,
    CUSTOMER_UPDATE,
    CUSTOMER_DELETE,
    CUSTOMER_GET_BY_CITIZEN,


    DASHBOARD_GET_DATA,
    DASHBOARD_PEAK_HOURS,
    EMAIL_SEND, DASHBOARD_GET_ROOMS,
    DASHBOARD_ORDER_STATISTICS,
    DASHBOARD_GET_DATA_EMPLOYEE,

    SURCHARGE_GET_BY_ID,
    SURCHARGE_GET_ALL,
    SURCHARGE_GET_BY_NAME,
    SURCHARGE_GET_BY_KEYWORDS,
    SURCHARGE_CREATE,
    SURCHARGE_UPDATE,
    SURCHARGE_DELETE,

    ROLE_GET_BY_ID,

    DENOMINATION_AVAILABLE,
    DENOMINATION_DETAIL_SAVE_ALL,


    EXPORT_EXCEL,
    IMPORT_AMENITIES,
    IMPORT_PROMOTIONS,
    IMPORT_CUSTOMERS,
    IMPORT_EMPLOYEES,
    IMPORT_SURCHARGES, IMPORT_ROOMS,

    PROMOTION_GET_BY_ID,
    PROMOTION_GET_ALL,
    PROMOTION_GET_BY_KEYWORDS,
    PROMOTION_CREATE,
    PROMOTION_UPDATE,
    PROMOTION_DELETE,
    PROMOTION_GET_ACTIVE,

    ROOM_TYPE_GET_BY_ID,
    ROOM_TYPE_GET_ALL,
    ROOM_TYPE_CREATE,
    ROOM_TYPE_UPDATE,
    ROOM_TYPE_DELETE,


    SHIFT_GET_BY_ID,
    SHIFT_GET_ALL,
    SHIFT_CREATE,
    SHIFT_UPDATE,
    SHIFT_DELETE,

    SHIFT_CLOSE_CREATE,
    SHIFT_CLOSE_GET_BY_ID,
    SHIFT_CLOSE_GET_ALL,
    SHIFT_CLOSE_UPDATE,
    SHIFT_CLOSE_DELETE,
    SHIFT_CLOSE_GET_BY_EMPLOYEE_SHIFT,
    SHIFT_CLOSE_GET_TOTAL_REVENUE,


    JASPERSOFT_EXPORT_ORDER_TO_PDF,

    ROOM_TOOL_ROOM_PRICE_WITH_DURATION,
    ROOM_TOOL_CALCULATE_EXTENSION_AMOUNT,
    ROOM_TOOL_EXTEND_ROOM_BOOKING,
    ROOM_TOOL_VALIDATE_TRANSFER,
    ROOM_TOOL_CALCULATE_SURCHARGE,
    ROOM_TOOL_CANCEL_ROOM_BOOKING,
    ROOM_TOOL_GET_ROOMS_BY_ORDER_AND_TYPE,
    ROOM_TOOL_GET_AVAILABLE_ROOMS_BY_TYPE,
    ROOM_TOOL_GET_ROOM_PRICE_BY_TYPE,
    ROOM_TOOL_CALCULATE_NEW_ROOM_PRICE_WITH_BOOKING_DURATION,
    ROOM_TOOL_TRANSFER_ROOMS,

    ROOM_OPTIMIZE_ROOM_ALLOCATION,
    ROOM_CHECK_ROOM_CAPACITY,
    ROOM_GET_AVAILABLE_ROOMS,
    ROOM_COUNT_AVAILABLE_ROOMS,
    ROOM_UPDATE_ROOM_STATUS_BATCH,
    ROOM_GET_ALL,
    ROOM_GET_BY_KEYWORD,
    ROOM_CAN_DELETE,
    ROOM_DELETE,
    ROOM_UPDATE,
    ROOM_CREATE,


    EMPLOYEE_SHIFT_GET_BY_ID,
    EMPLOYEE_SHIFT_GET_ALL,
    EMPLOYEE_SHIFT_CREATE,
    EMPLOYEE_SHIFT_UPDATE,
    EMPLOYEE_SHIFT_DELETE,
    EMPLOYEE_SHIFT_GET_BY_EMPLOYEE_AND_DATE,
    EMPLOYEE_SHIFT_GET_SHIFT_BY_DATE,
    EMPLOYEE_SHIFT_GET_WITH_DETAILS,
    EMPLOYEE_SHIFT_GET_TOTAL_REVENUE,
    EMPLOYEE_SHIFT_GET_ACTIVE_OPEN_SHIFTS,
    EMPLOYEE_SHIFT_GET_ALL_SHIFTS_BY_DATE,

    PAYMENT_CREATE,
    PAYMENT_QUERY,

    SURCHARGE_DETAIL_GET_BY_ORDER,
    SURCHARGE_DETAIL_CREATE,
    SURCHARGE_DETAIL_UPDATE,
    SURCHARGE_DETAIL_DELETE,
    SURCHARGE_DETAIL_CREATE_LIST,



}
