/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.booking2;

import iuh.fit.se.group1.dto.*;
import iuh.fit.se.group1.enums.BookingType;
import iuh.fit.se.group1.network.Response;
import iuh.fit.se.group1.network.client.service.SurchargeServiceClient;
import iuh.fit.se.group1.ui.component.custom.Button;
import iuh.fit.se.group1.util.Constants;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * @author THIS PC
 */
public class MainFlow5 extends JPanel {

    private static final long SURCHARGE_HOLIDAY = 50_000;

    public Button getBtnPrev() {
        return btnPrev;
    }

    public Button getBtnComplete() {
        return btnComplete;
    }

    public Button getBtnCancel() {
        return btnCancel;
    }

    public void setBtnCancel(Button btnCancel) {
        this.btnComplete = btnCancel;
    }

    public void setBtnComplete(Button btnComplete) {
        this.btnCancel = btnComplete;
    }

    public void setBtnPrev(Button btnPrev) {
        this.btnPrev = btnPrev;
    }

    /**
     * Creates new form MainFlow5
     */
    public MainFlow5() {
        initComponents();
        tbl.setGridColor(new Color(10, 10, 10));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new JPanel();
        lbl1 = new JLabel();
        lbl2 = new JLabel();
        pnl2 = new JPanel();
        lbl3 = new JLabel();
        lblCheckIn = new JLabel();
        spn1 = new JSeparator();
        lbl4 = new JLabel();
        lblCheckOut = new JLabel();
        spn2 = new JSeparator();
        lbl5 = new JLabel();
        lblNumberOfAdult = new JLabel();
        spn3 = new JSeparator();
        lbl6 = new JLabel();
        lblDoubleRooms = new JLabel();
        lbl7 = new JLabel();
        lblSingleRooms = new JLabel();
        spn4 = new JSeparator();
        lbl8 = new JLabel();
        lblNumberOfChildren = new JLabel();
        spn5 = new JSeparator();
        lbl20 = new JLabel();
        lblBookingType = new JLabel();
        spn6 = new JSeparator();
        pnl3 = new JPanel();
        lbl18 = new JLabel();
        lblTotalRoom = new JLabel();
        pnl4 = new JPanel();
        scr = new JScrollPane();
        tbl = new JTable();
        pnl5 = new JPanel();
        lbl17 = new JLabel();
        lblTotalAmenity = new JLabel();
        pnl6 = new JPanel();
        lbl9 = new JLabel();
        lblFullName = new JLabel();
        lbl10 = new JLabel();
        lblPhone = new JLabel();
        lblEmail = new JLabel();
        lbl11 = new JLabel();
        lblCitizenid = new JLabel();
        lbl12 = new JLabel();
        lbl14 = new JLabel();
        lblDob = new JLabel();
        lbl13 = new JLabel();
        lblGender = new JLabel();
        pnl7 = new JPanel();
        lbl15 = new JLabel();
        lbl16 = new JLabel();
        lblDeposit = new JLabel();
        lblTotalPrice = new JLabel();
        btnCancel = new Button();
        btnPrev = new Button();
        lblSurchargeHolidayName = new JLabel();
        lblSurchargeHoliday = new JLabel();
        btnComplete = new Button();

        setBackground(new Color(255, 255, 255));

        pnl1.setBackground(new Color(185, 215, 254));

        lbl1.setFont(new Font("Segoe UI", 1, 24)); // NOI18N
        lbl1.setForeground(new Color(0, 0, 0));
        lbl1.setText("Nhập thông tin khách hàng");

        lbl2.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        lbl2.setForeground(new Color(0, 0, 0));
        lbl2.setText("Vui lòng nhập thông tin chính xác ");

        GroupLayout pnl1Layout = new GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
                pnl1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(pnl1Layout.createSequentialGroup()
                                .addContainerGap(40, Short.MAX_VALUE)
                                .addGroup(pnl1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl1, GroupLayout.PREFERRED_SIZE, 342, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl2, GroupLayout.PREFERRED_SIZE, 741, GroupLayout.PREFERRED_SIZE)))
        );
        pnl1Layout.setVerticalGroup(
                pnl1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(pnl1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lbl1)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl2)
                                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnl2.setBackground(new Color(255, 255, 255));
        pnl2.setBorder(BorderFactory.createTitledBorder(null, "Chi tiết đặt phòng", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new Font("Segoe UI", 1, 13), new Color(102, 102, 102))); // NOI18N

        lbl3.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lbl3.setForeground(new Color(91, 91, 91));
        lbl3.setText("Ngày nhận phòng:");

        lblCheckIn.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lblCheckIn.setForeground(new Color(91, 91, 91));
        lblCheckIn.setText("n/a");

        spn1.setBackground(new Color(91, 91, 91));
        spn1.setForeground(new Color(91, 91, 91));
        spn1.setFont(new Font("Segoe UI", 1, 12)); // NOI18N

        lbl4.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lbl4.setForeground(new Color(91, 91, 91));
        lbl4.setText("Ngày trả phòng:");

        lblCheckOut.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lblCheckOut.setForeground(new Color(91, 91, 91));
        lblCheckOut.setText("n/a");

        spn2.setBackground(new Color(91, 91, 91));
        spn2.setForeground(new Color(91, 91, 91));
        spn2.setFont(new Font("Segoe UI", 1, 12)); // NOI18N

        lbl5.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lbl5.setForeground(new Color(91, 91, 91));
        lbl5.setText("Số người lớn:");

        lblNumberOfAdult.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lblNumberOfAdult.setForeground(new Color(91, 91, 91));
        lblNumberOfAdult.setText("n/a");

        spn3.setBackground(new Color(91, 91, 91));
        spn3.setForeground(new Color(91, 91, 91));
        spn3.setFont(new Font("Segoe UI", 1, 12)); // NOI18N

        lbl6.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lbl6.setForeground(new Color(91, 91, 91));
        lbl6.setText("Phòng đôi:");

        lblDoubleRooms.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lblDoubleRooms.setForeground(new Color(91, 91, 91));
        lblDoubleRooms.setText("n/a");

        lbl7.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lbl7.setForeground(new Color(91, 91, 91));
        lbl7.setText("Phòng đơn:");

        lblSingleRooms.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lblSingleRooms.setForeground(new Color(91, 91, 91));
        lblSingleRooms.setText("n/a");

        spn4.setBackground(new Color(91, 91, 91));
        spn4.setForeground(new Color(91, 91, 91));
        spn4.setFont(new Font("Segoe UI", 1, 12)); // NOI18N

        lbl8.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lbl8.setForeground(new Color(91, 91, 91));
        lbl8.setText("Số trẻ em:");

        lblNumberOfChildren.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lblNumberOfChildren.setForeground(new Color(91, 91, 91));
        lblNumberOfChildren.setText("n/a");

        spn5.setBackground(new Color(91, 91, 91));
        spn5.setForeground(new Color(91, 91, 91));
        spn5.setFont(new Font("Segoe UI", 1, 12)); // NOI18N

        lbl20.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lbl20.setForeground(new Color(91, 91, 91));
        lbl20.setText("Kiểu đặt phòng");

        lblBookingType.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lblBookingType.setForeground(new Color(91, 91, 91));
        lblBookingType.setText("n/a");

        spn6.setBackground(new Color(91, 91, 91));
        spn6.setForeground(new Color(91, 91, 91));
        spn6.setFont(new Font("Segoe UI", 1, 12)); // NOI18N

        GroupLayout pnl2Layout = new GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
                pnl2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(pnl2Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(pnl2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(pnl2Layout.createSequentialGroup()
                                                .addComponent(lbl20, GroupLayout.PREFERRED_SIZE, 231, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblBookingType, GroupLayout.PREFERRED_SIZE, 484, GroupLayout.PREFERRED_SIZE))
                                        .addComponent(spn6, GroupLayout.PREFERRED_SIZE, 711, GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnl2Layout.createSequentialGroup()
                                                .addComponent(lbl6, GroupLayout.PREFERRED_SIZE, 231, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblDoubleRooms, GroupLayout.PREFERRED_SIZE, 484, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnl2Layout.createSequentialGroup()
                                                .addComponent(lbl5, GroupLayout.PREFERRED_SIZE, 231, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblNumberOfAdult, GroupLayout.PREFERRED_SIZE, 484, GroupLayout.PREFERRED_SIZE))
                                        .addComponent(spn2, GroupLayout.PREFERRED_SIZE, 711, GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnl2Layout.createSequentialGroup()
                                                .addComponent(lbl4, GroupLayout.PREFERRED_SIZE, 231, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblCheckOut, GroupLayout.PREFERRED_SIZE, 484, GroupLayout.PREFERRED_SIZE))
                                        .addComponent(spn1, GroupLayout.PREFERRED_SIZE, 711, GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnl2Layout.createSequentialGroup()
                                                .addComponent(lbl3, GroupLayout.PREFERRED_SIZE, 231, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblCheckIn, GroupLayout.PREFERRED_SIZE, 484, GroupLayout.PREFERRED_SIZE))
                                        .addComponent(spn3, GroupLayout.PREFERRED_SIZE, 711, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spn5, GroupLayout.PREFERRED_SIZE, 711, GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnl2Layout.createSequentialGroup()
                                                .addComponent(lbl8, GroupLayout.PREFERRED_SIZE, 231, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblNumberOfChildren, GroupLayout.PREFERRED_SIZE, 484, GroupLayout.PREFERRED_SIZE))
                                        .addComponent(spn4, GroupLayout.PREFERRED_SIZE, 711, GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnl2Layout.createSequentialGroup()
                                                .addComponent(lbl7, GroupLayout.PREFERRED_SIZE, 231, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblSingleRooms, GroupLayout.PREFERRED_SIZE, 484, GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnl2Layout.setVerticalGroup(
                pnl2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(pnl2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnl2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl3)
                                        .addComponent(lblCheckIn))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spn1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl4)
                                        .addComponent(lblCheckOut))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spn2, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl5)
                                        .addComponent(lblNumberOfAdult))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spn3, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl8)
                                        .addComponent(lblNumberOfChildren))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spn5, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl7)
                                        .addComponent(lblSingleRooms))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spn4, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl6)
                                        .addComponent(lblDoubleRooms))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spn6, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl20)
                                        .addComponent(lblBookingType))
                                .addContainerGap())
        );

        pnl3.setBackground(new Color(185, 215, 254));

        lbl18.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        lbl18.setForeground(new Color(0, 0, 0));
        lbl18.setText("Thành tiền phòng");

        lblTotalRoom.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalRoom.setForeground(new Color(77, 134, 168));
        lblTotalRoom.setHorizontalAlignment(SwingConstants.RIGHT);
        lblTotalRoom.setText("n/a");

        GroupLayout pnl3Layout = new GroupLayout(pnl3);
        pnl3.setLayout(pnl3Layout);
        pnl3Layout.setHorizontalGroup(
                pnl3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, pnl3Layout.createSequentialGroup()
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl18, GroupLayout.PREFERRED_SIZE, 319, GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(lblTotalRoom, GroupLayout.PREFERRED_SIZE, 295, GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
        );
        pnl3Layout.setVerticalGroup(
                pnl3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, pnl3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl18, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTotalRoom, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE))
        );

        pnl4.setBackground(new Color(255, 255, 255));
        pnl4.setBorder(BorderFactory.createTitledBorder(null, "Dịch vụ bổ sung", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new Font("Segoe UI", 1, 13), new Color(102, 102, 102))); // NOI18N
        pnl4.setForeground(new Color(255, 255, 255));

        scr.setBackground(new Color(255, 255, 255));

        tbl.setBackground(new Color(255, 255, 255));
        tbl.setModel(new DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "STT", "Tên dịch vụ", "Giá", "Số lượng"
                }
        ));
        tbl.getTableHeader().setReorderingAllowed(false);
        scr.setViewportView(tbl);

        GroupLayout pnl4Layout = new GroupLayout(pnl4);
        pnl4.setLayout(pnl4Layout);
        pnl4Layout.setHorizontalGroup(
                pnl4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(pnl4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(scr)
                                .addContainerGap())
        );
        pnl4Layout.setVerticalGroup(
                pnl4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(pnl4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(scr, GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pnl5.setBackground(new Color(185, 215, 254));

        lbl17.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        lbl17.setForeground(new Color(0, 0, 0));
        lbl17.setText("Thành tiền dịch vụ");

        lblTotalAmenity.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalAmenity.setForeground(new Color(77, 134, 168));
        lblTotalAmenity.setHorizontalAlignment(SwingConstants.RIGHT);
        lblTotalAmenity.setText("n/a");

        GroupLayout pnl5Layout = new GroupLayout(pnl5);
        pnl5.setLayout(pnl5Layout);
        pnl5Layout.setHorizontalGroup(
                pnl5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, pnl5Layout.createSequentialGroup()
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl17, GroupLayout.PREFERRED_SIZE, 319, GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(lblTotalAmenity, GroupLayout.PREFERRED_SIZE, 295, GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
        );
        pnl5Layout.setVerticalGroup(
                pnl5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, pnl5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl17, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTotalAmenity, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE))
        );

        pnl6.setBackground(new Color(255, 255, 255));
        pnl6.setBorder(BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new Font("Segoe UI", 1, 13), new Color(102, 102, 102))); // NOI18N

        lbl9.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lbl9.setForeground(new Color(91, 91, 91));
        lbl9.setText("Họ và tên:");

        lblFullName.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lblFullName.setForeground(new Color(91, 91, 91));
        lblFullName.setText("n/a");

        lbl10.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lbl10.setForeground(new Color(91, 91, 91));
        lbl10.setText("Số điện thoại:");

        lblPhone.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lblPhone.setForeground(new Color(91, 91, 91));
        lblPhone.setText("n/a");

        lblEmail.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lblEmail.setForeground(new Color(91, 91, 91));
        lblEmail.setText("n/a");

        lbl11.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lbl11.setForeground(new Color(91, 91, 91));
        lbl11.setText("Email:");

        lblCitizenid.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lblCitizenid.setForeground(new Color(91, 91, 91));
        lblCitizenid.setText("n/a");

        lbl12.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lbl12.setForeground(new Color(91, 91, 91));
        lbl12.setText("Ngày sinh:");

        lbl14.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lbl14.setForeground(new Color(91, 91, 91));
        lbl14.setText("CCCD/Hộ chiếu:");

        lblDob.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lblDob.setForeground(new Color(91, 91, 91));
        lblDob.setText("n/a");

        lbl13.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lbl13.setForeground(new Color(91, 91, 91));
        lbl13.setText("Giới tính:");

        lblGender.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lblGender.setForeground(new Color(91, 91, 91));
        lblGender.setText("n/a");

        GroupLayout pnl6Layout = new GroupLayout(pnl6);
        pnl6.setLayout(pnl6Layout);
        pnl6Layout.setHorizontalGroup(
                pnl6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(pnl6Layout.createSequentialGroup()
                                .addGroup(pnl6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(pnl6Layout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addGroup(pnl6Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                        .addGroup(pnl6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                .addGroup(pnl6Layout.createSequentialGroup()
                                                                        .addComponent(lbl10, GroupLayout.PREFERRED_SIZE, 185, GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(0, 0, 0)
                                                                        .addComponent(lblPhone, GroupLayout.PREFERRED_SIZE, 455, GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(pnl6Layout.createSequentialGroup()
                                                                        .addComponent(lbl9, GroupLayout.PREFERRED_SIZE, 185, GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(0, 0, 0)
                                                                        .addComponent(lblFullName, GroupLayout.PREFERRED_SIZE, 455, GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(pnl6Layout.createSequentialGroup()
                                                                .addGroup(pnl6Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(lbl14, GroupLayout.PREFERRED_SIZE, 185, GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lbl11, GroupLayout.PREFERRED_SIZE, 185, GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lbl12, GroupLayout.PREFERRED_SIZE, 185, GroupLayout.PREFERRED_SIZE))
                                                                .addGap(0, 0, 0)
                                                                .addComponent(lblEmail, GroupLayout.PREFERRED_SIZE, 455, GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(lbl13, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(pnl6Layout.createSequentialGroup()
                                                .addGap(210, 210, 210)
                                                .addGroup(pnl6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblDob, GroupLayout.PREFERRED_SIZE, 185, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblCitizenid, GroupLayout.PREFERRED_SIZE, 455, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblGender, GroupLayout.PREFERRED_SIZE, 94, GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 106, Short.MAX_VALUE))
        );
        pnl6Layout.setVerticalGroup(
                pnl6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(pnl6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnl6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl9)
                                        .addComponent(lblFullName))
                                .addGap(10, 10, 10)
                                .addGroup(pnl6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl10)
                                        .addComponent(lblPhone))
                                .addGap(10, 10, 10)
                                .addGroup(pnl6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl11)
                                        .addComponent(lblEmail))
                                .addGap(10, 10, 10)
                                .addGroup(pnl6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblCitizenid)
                                        .addComponent(lbl14))
                                .addGap(10, 10, 10)
                                .addGroup(pnl6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl12)
                                        .addComponent(lblDob))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnl6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl13)
                                        .addComponent(lblGender))
                                .addContainerGap(9, Short.MAX_VALUE))
        );

        pnl7.setBackground(new Color(153, 255, 153));

        lbl15.setFont(new Font("Segoe UI", 1, 13)); // NOI18N
        lbl15.setForeground(new Color(91, 91, 91));
        lbl15.setText("Tổng thanh toán:");

        lbl16.setFont(new Font("Segoe UI", 1, 13)); // NOI18N
        lbl16.setForeground(new Color(91, 91, 91));
        lbl16.setHorizontalAlignment(SwingConstants.RIGHT);
        lbl16.setText("Đặt cọc 30% tiền phòng");

        lblDeposit.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        lblDeposit.setForeground(new Color(251, 128, 5));
        lblDeposit.setHorizontalAlignment(SwingConstants.RIGHT);
        lblDeposit.setText("N/A");

        lblTotalPrice.setFont(new Font("Segoe UI", 1, 24)); // NOI18N
        lblTotalPrice.setForeground(new Color(0, 153, 51));
        lblTotalPrice.setText("N/A");

        GroupLayout pnl7Layout = new GroupLayout(pnl7);
        pnl7.setLayout(pnl7Layout);
        pnl7Layout.setHorizontalGroup(
                pnl7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(pnl7Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(pnl7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl15, GroupLayout.PREFERRED_SIZE, 156, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblTotalPrice, GroupLayout.PREFERRED_SIZE, 192, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnl7Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbl16, GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(lblDeposit, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(14, 14, 14))
        );
        pnl7Layout.setVerticalGroup(
                pnl7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(pnl7Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(pnl7Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl15)
                                        .addComponent(lbl16))
                                .addGap(0, 0, 0)
                                .addGroup(pnl7Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblDeposit, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblTotalPrice, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9))
        );

        btnCancel.setBackground(new Color(204, 0, 0));
        btnCancel.setForeground(new Color(255, 255, 255));
        btnCancel.setText("Hủy thao tác");
        btnCancel.setBorderRadius(5);
        btnCancel.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnPrev.setBackground(new Color(227, 227, 227));
        btnPrev.setForeground(new Color(77, 134, 168));
        btnPrev.setText("QUAY LẠI");
        btnPrev.setBorderRadius(5);
        btnPrev.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        lblSurchargeHolidayName.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        lblSurchargeHolidayName.setForeground(new Color(255, 51, 51));
        lblSurchargeHolidayName.setText("Phụ thu ngày lễ");

        lblSurchargeHoliday.setFont(new Font("Segoe UI", 3, 14)); // NOI18N
        lblSurchargeHoliday.setForeground(new Color(255, 0, 0));
        lblSurchargeHoliday.setHorizontalAlignment(SwingConstants.RIGHT);
        lblSurchargeHoliday.setText("N/a");

        btnComplete.setBackground(new Color(13, 200, 7));
        btnComplete.setForeground(new Color(255, 255, 255));
        btnComplete.setText("XÁC NHẬN ĐẶT PHÒNG");
        btnComplete.setBorderRadius(5);
        btnComplete.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(34, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblSurchargeHolidayName, GroupLayout.PREFERRED_SIZE, 319, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblSurchargeHoliday, GroupLayout.PREFERRED_SIZE, 229, GroupLayout.PREFERRED_SIZE))
                                        .addComponent(pnl5, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnl1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnl2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnl3, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnl4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnl6, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnl7, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnPrev, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnCancel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addGap(203, 203, 203)))
                                .addContainerGap(36, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap(628, Short.MAX_VALUE)
                                        .addComponent(btnComplete, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(pnl1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnl2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnl3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnl4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnl5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnl6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblSurchargeHolidayName)
                                        .addComponent(lblSurchargeHoliday))
                                .addGap(18, 18, 18)
                                .addComponent(pnl7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnCancel, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnPrev, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap(1049, Short.MAX_VALUE)
                                        .addComponent(btnComplete, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCompleteActionPerformed


    public void setAmenity(List<AmenityDTO> selectedAmenities) {
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        model.setRowCount(0);
        int index = 1;
        BigDecimal total = BigDecimal.ZERO;
        for (AmenityDTO amenity : selectedAmenities) {
            Object[] row = new Object[]{
                    index++,
                    amenity.getNameAmenity(),
                    Constants.VND_FORMAT.format(amenity.getPrice()),
                    amenity.getQuantity()
            };
            total = total.add(amenity.getPrice().multiply(BigDecimal.valueOf(amenity.getQuantity())));
            model.addRow(row);
        }
        lblTotalAmenity.setText(Constants.VND_FORMAT.format(total));
    }

    public void setupCustomer(CustomerDTO customer) {
        lblFullName.setText(customer.getFullName());
        lblPhone.setText(customer.getPhone());
        lblEmail.setText(customer.getEmail() != null ? customer.getEmail() : "N/A");
        lblCitizenid.setText(customer.getCitizenId());
        lblDob.setText(customer.getDateOfBirth().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        lblGender.setText(customer.isGender() ? "Nữ" : "Nam");
    }

    public void setInfoBooking(
            String checkIn,
            String checkOut,
            String numberOfAdult,
            String numberOfChildren,
            String bookingType,
            List<RoomSelection> selectedRoom,
            String totalRoom,
            boolean isHoliday
    ) {


        lblCheckIn.setText(checkIn);
        lblCheckOut.setText(checkOut);
        lblNumberOfAdult.setText(numberOfAdult);
        lblNumberOfChildren.setText(numberOfChildren);
        lblBookingType.setText(bookingType);
        lblTotalRoom.setText(totalRoom);

        Map<String, List<RoomSelection>> map = selectedRoom.stream()
                .collect(Collectors.groupingBy(RoomSelection::getRoomType));

        for (Map.Entry<String, List<RoomSelection>> entry : map.entrySet()) {
            String roomTypeKey = entry.getKey();
            var listRoom = entry.getValue();
            String valueNew = listRoom.stream()
                    .map(RoomSelection::getNumber)
                    .collect(Collectors.joining(", "));
            if (roomTypeKey.equals("SINGLE")) {
                lblSingleRooms.setText(valueNew);
            } else if (roomTypeKey.equals("DOUBLE")) {
                lblDoubleRooms.setText(valueNew);
            }
        }

        var deposit = Constants.parseVND(totalRoom) * 0.3;
        lblDeposit.setText(Constants.VND_FORMAT.format(deposit));


        var holidayPrice = isHoliday ? SURCHARGE_HOLIDAY * selectedRoom.size() : 0;

        var totalPrice = Constants.parseVND(totalRoom) + Constants.parseVND(lblTotalAmenity.getText());

        lblSurchargeHoliday.setText(holidayPrice != 0 ? Constants.VND_FORMAT.format(holidayPrice) : "Không có");

        lblTotalPrice.setText(Constants.VND_FORMAT.format(totalPrice + holidayPrice));
    }


    public OrderResult buildOrder(
            EmployeeDTO currentEmployee,
            CustomerDTO customer,
            List<RoomSelection> selectedRooms,
            SurchargeServiceClient surchargeService) throws Exception {

        OrderDTO order = new OrderDTO();
        order.setCustomer(customer);
        order.setDeposit(BigDecimal.valueOf(Constants.parseVND(lblDeposit.getText())));
        order.setOrderDate(LocalDateTime.now());
        order.setTotalAmount(BigDecimal.valueOf(Constants.parseVND(lblTotalPrice.getText())));
        order.setEmployee(currentEmployee);

        order.setOrderType(new OrderTypeDTO());

        LocalDateTime checkIn = LocalDateTime.parse(
                lblCheckIn.getText(),
                DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")
        );
        LocalDateTime checkOut = LocalDateTime.parse(
                lblCheckOut.getText(),
                DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")
        );


        LocalDateTime now = LocalDateTime.now();

        // Nếu checkIn trước now + 1 giờ → đặt trước
        if (!checkIn.isBefore(now.plusHours(1))) {
            order.setOrderType(OrderTypeDTO.builder().orderTypeId(3L).build()); // loại đặt trước
        } else {
            order.setOrderType(OrderTypeDTO.builder().orderTypeId(2L).build()); // loại ở ngay
        }

        List<BookingViewDTO> bookings = new ArrayList<>();

        for (RoomSelection roomSelection : selectedRooms) {
            BookingViewDTO booking = new BookingViewDTO();
            booking.setRoom(RoomViewDTO.builder().roomId(roomSelection.getId()).build());
            booking.setCheckInDate(checkIn);
            booking.setCheckOutDate(checkOut);
            booking.setBookingType(BookingType.fromString(lblBookingType.getText()));
            bookings.add(booking);
        }

        order.setBookings(bookings);


        if (lblSurchargeHoliday.getText().equals("N/a") || lblSurchargeHoliday.getText().equals("Không có")) {
            return new OrderResult(order, null);
        }

        Response response = surchargeService.getSurchargeByName(lblSurchargeHolidayName.getText().trim());

        if (response == null || response.getCode() != 200) {
            JOptionPane.showMessageDialog(this, "Lỗi khi lấy thông tin phụ thu ngày lễ từ server: " + (response != null ? response.getMessage() : "No response"), "Lỗi", JOptionPane.ERROR_MESSAGE);
            throw new RuntimeException("Lỗi khi lấy thông tin phụ thu ngày lễ");

        }

        SurchargeDTO surchargeHoliday = (SurchargeDTO) response.getData();

        SurchargeDetailDTO surchargeDetail = new SurchargeDetailDTO();
        surchargeDetail.setSurcharge(surchargeHoliday);
        surchargeDetail.setQuantity(selectedRooms.size());

        return new OrderResult(order, surchargeDetail);

    }


    public void reset() {
        lblCheckIn.setText("");
        lblCheckOut.setText("");
        lblNumberOfAdult.setText("");
        lblNumberOfChildren.setText("");
        lblSingleRooms.setText("");
        lblDoubleRooms.setText("");
        lblBookingType.setText("");
        lblTotalRoom.setText("");
        lblTotalAmenity.setText("");
        lblFullName.setText("");
        lblPhone.setText("");
        lblEmail.setText("");
        lblCitizenid.setText("");
        lblDob.setText("");
        lblGender.setText("");
        lblSurchargeHoliday.setText("");
        lblDeposit.setText("");
        lblTotalPrice.setText("");

        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        model.setRowCount(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Button btnCancel;
    private Button btnComplete;
    private Button btnPrev;
    private JLabel lbl1;
    private JLabel lbl10;
    private JLabel lbl11;
    private JLabel lbl12;
    private JLabel lbl13;
    private JLabel lbl14;
    private JLabel lbl15;
    private JLabel lbl16;
    private JLabel lbl17;
    private JLabel lbl18;
    private JLabel lbl2;
    private JLabel lbl20;
    private JLabel lbl3;
    private JLabel lbl4;
    private JLabel lbl5;
    private JLabel lbl6;
    private JLabel lbl7;
    private JLabel lbl8;
    private JLabel lbl9;
    private JLabel lblBookingType;
    private JLabel lblCheckIn;
    private JLabel lblCheckOut;
    private JLabel lblCitizenid;
    private JLabel lblDeposit;
    private JLabel lblDob;
    private JLabel lblDoubleRooms;
    private JLabel lblEmail;
    private JLabel lblFullName;
    private JLabel lblGender;
    private JLabel lblNumberOfAdult;
    private JLabel lblNumberOfChildren;
    private JLabel lblPhone;
    private JLabel lblSingleRooms;
    private JLabel lblSurchargeHoliday;
    private JLabel lblSurchargeHolidayName;
    private JLabel lblTotalAmenity;
    private JLabel lblTotalPrice;
    private JLabel lblTotalRoom;
    private JPanel pnl1;
    private JPanel pnl2;
    private JPanel pnl3;
    private JPanel pnl4;
    private JPanel pnl5;
    private JPanel pnl6;
    private JPanel pnl7;
    private JScrollPane scr;
    private JSeparator spn1;
    private JSeparator spn2;
    private JSeparator spn3;
    private JSeparator spn4;
    private JSeparator spn5;
    private JSeparator spn6;
    private JTable tbl;
    // End of variables declaration//GEN-END:variables
}
