package iuh.fit.se.group1.ui.component.booking2;

import iuh.fit.se.group1.dto.*;
import iuh.fit.se.group1.network.Response;
import iuh.fit.se.group1.network.client.service.RoomServiceClient;
import iuh.fit.se.group1.ui.component.custom.Button;
import iuh.fit.se.group1.ui.component.custom.message.CustomDialog;
import iuh.fit.se.group1.util.Constants;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.swing.*;
import java.awt.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 * @author THIS PC
 */
public class MainFlow2 extends JPanel {
    public JLabel getLblTotalRoom() {
        return lblTotalRoom;
    }

    public void setLblTotalRoom(JLabel lblTotalRoom) {
        this.lblTotalRoom = lblTotalRoom;
    }

    private static final Logger log = LoggerFactory.getLogger(MainFlow2.class);

    /**
     * Creates new form MainFlow2
     */
    public MainFlow2() {
        initComponents();
        String text =
                "<html>"
                        + "<span>Chọn phòng phù hợp với nhu cầu</span><br>"
                        + "<u>Lưu ý :</u><br>"
                        + "<ul>"
                        + "  <li>Người dưới 12 tuổi được tính là <b>trẻ em</b></li>"
                        + "  <li>Phòng đơn có thể chứa tối đa 2 người lớn + 1 trẻ em</li>"
                        + "  <li>Phòng đôi có thể chứa tối đa 4 người lớn + 2 trẻ em</li>"
                        + "  <li>Đề xuất cho khách hàng XXX : 4 phòng đơn + 2 phòng đôi</li>"
                        + "</ul>"
                        + "</html>";

        lbl1.setText(text);

        // JScroll pane không hiện kéo
        scr.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scr.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new JPanel();
        lbl2 = new JLabel();
        lbl1 = new JLabel();
        btnNext = new Button();
        btnPrev = new Button();
        scr = new JScrollPane();
        tbl = new CustomTable();
        lblMessage = new JLabel();
        lbl = new JLabel();
        lblTotalRoom = new JLabel();

        setBackground(new Color(255, 255, 255));

        pnl1.setBackground(new Color(185, 215, 254));

        lbl2.setFont(new Font("Segoe UI", 1, 24)); // NOI18N
        lbl2.setForeground(new Color(0, 0, 0));
        lbl2.setText("Chọn phòng");

        lbl1.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        lbl1.setForeground(new Color(0, 0, 0));
        lbl1.setText("Chọn phòng phù hợp với nhu cầu:");

        GroupLayout pnl1Layout = new GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
                pnl1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(pnl1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(pnl1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl2, GroupLayout.PREFERRED_SIZE, 486, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl1, GroupLayout.PREFERRED_SIZE, 720, GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(48, Short.MAX_VALUE))
        );
        pnl1Layout.setVerticalGroup(
                pnl1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(pnl1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lbl2)
                                .addGap(7, 7, 7)
                                .addComponent(lbl1, GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                .addContainerGap())
        );

        btnNext.setBackground(new Color(77, 134, 168));
        btnNext.setForeground(new Color(255, 255, 255));
        btnNext.setText("TIẾP THEO");
        btnNext.setBorderRadius(5);
        btnNext.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrev.setBackground(new Color(227, 227, 227));
        btnPrev.setForeground(new Color(77, 134, 168));
        btnPrev.setText("QUAY LẠI");
        btnPrev.setBorderRadius(5);
        btnPrev.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        tbl.setBackground(new Color(255, 255, 255));
        tbl.setForeground(new Color(51, 51, 51));
        scr.setViewportView(tbl);

        lblMessage.setFont(new Font("Segoe UI", 3, 14)); // NOI18N
        lblMessage.setForeground(new Color(255, 0, 0));
        lblMessage.setText("Số khách chưa được xếp");

        lbl.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lbl.setForeground(new Color(0, 0, 0));
        lbl.setText("Tổng tiền:");

        lblTotalRoom.setFont(new Font("Segoe UI", 3, 14)); // NOI18N
        lblTotalRoom.setForeground(new Color(255, 0, 0));
        lblTotalRoom.setHorizontalAlignment(SwingConstants.RIGHT);
        lblTotalRoom.setText("jLabel2");

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbl, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 480, Short.MAX_VALUE)
                                                .addComponent(lblTotalRoom, GroupLayout.PREFERRED_SIZE, 255, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(btnPrev, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnNext, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE))
                                                .addComponent(pnl1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(scr)
                                                .addComponent(lblMessage, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(pnl1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(scr, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblTotalRoom))
                                .addGap(1, 1, 1)
                                .addComponent(lblMessage)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnNext, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnPrev, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    public Button getBtnNext() {
        return btnNext;
    }

    public void setBtnNext(Button btnNext) {
        this.btnNext = btnNext;
    }

    public Button getBtnPrev() {
        return btnPrev;
    }

    public void setBtnPrev(Button btnPrev) {

        this.btnPrev = btnPrev;
    }


    public Long getPriceFromBookingTypeAndRoomType(int bookingType, RoomDTO roomDTO, int timePlus) {
        if (bookingType == 0) { // Theo giờ
            return roomDTO.getHourlyRate().longValueExact() + ((timePlus - 1) * roomDTO.getAdditionalHourRate().longValueExact());
        } else if (bookingType == 1) { // Theo ngày
            return roomDTO.getDailyRate().longValueExact() * timePlus;
        } else if (bookingType == 2) { // qua đêm
            return roomDTO.getOvernightRate().longValueExact();
        }
        return 0L;
    }

    public boolean updateRoomList(AvailableRoomCountResponse availableRooms, int adults, int children, RoomServiceClient roomService, int bookingIndex, int timePlus) {


        long singleQuantity = availableRooms.getSingleAvailable();
        long doubleQuantity = availableRooms.getDoubleAvailable();

        RoomDTO singleRoomDTO = availableRooms.getSingleRoom();
        RoomDTO doubleRoomDTO = availableRooms.getDoubleRoom();

        Response response = null;
        try {
            response = roomService.optimizeRoomAllocation((int) singleQuantity, (int) doubleQuantity, adults, children);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

        if (response == null || response.getCode() != 200) {

            JOptionPane.showMessageDialog(this, "Lỗi khi tối ưu phân bổ phòng: " + (response != null ? response.getMessage() : "Không có phản hồi"), "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        OptimizeRoomAllocationResponse optimizeRoomAllocation = (OptimizeRoomAllocationResponse) response.getData();
        if (optimizeRoomAllocation.getUnaccommodatedGuests() > 0) {
            CustomDialog.showMessage(this, "Không đủ phòng để đáp ứng số lượng khách!", "Không đủ phòng", CustomDialog.MessageType.ERROR, 500, 200);
            return false;
        }

        var model = (CustomTable.CustomTableModel) tbl.getModel();

// Row 0 - SINGLE
        model.setValueAt("Phòng đơn", 0, 0);
        model.setValueAt(singleRoomDTO.getCapacity(), 0, 1);
        model.setValueAt(getPriceFromBookingTypeAndRoomType(bookingIndex, singleRoomDTO, timePlus), 0, 2);
        model.setValueAt(singleQuantity, 0, 4);
        model.setValueAt(optimizeRoomAllocation.getUsedSingleRooms(), 0, 5);

// Row 1 - DOUBLE
        model.setValueAt("Phòng đôi", 1, 0);
        model.setValueAt(doubleRoomDTO.getCapacity(), 1, 1);
        model.setValueAt(getPriceFromBookingTypeAndRoomType(bookingIndex, doubleRoomDTO, timePlus), 1, 2);
        model.setValueAt(doubleQuantity, 1, 4);
        model.setValueAt(optimizeRoomAllocation.getUsedDoubleRooms(), 1, 5);

        int unaccommodatedGuests = (int) optimizeRoomAllocation.getUnaccommodatedGuests();

        if (unaccommodatedGuests > 0) {

            int unaccommodatedAdults = Math.toIntExact(optimizeRoomAllocation.getUnaccommodatedAdults());
            int unaccommodatedChildren = Math.toIntExact(optimizeRoomAllocation.getUnaccommodatedChildren());

            String msg;

            if (unaccommodatedChildren > 0) {
                msg = "Số khách chưa được xếp: " + unaccommodatedGuests +
                        " (Người lớn: " + unaccommodatedAdults +
                        ", Trẻ em: " + unaccommodatedChildren + ")";
            } else {
                msg = "Số khách chưa được xếp: " + unaccommodatedGuests +
                        " (Người lớn: " + unaccommodatedAdults + ")";
            }

            lblMessage.setText(msg);
            lblMessage.setForeground(Color.RED);

        } else {
            lblMessage.setText("Tất cả khách đã được xếp phòng.");
            lblMessage.setForeground(new Color(0, 153, 0));

        }


        lblTotalRoom.setText(getTotalPriceRoom((Number) tbl.getValueAt(0, 3), (Number) tbl.getValueAt(1, 3)));

        tbl.setQuantityChangeListener((r, newQuantity) -> {
            Response res = roomService.checkRoomCapacity(adults,
                    children,
                    (Number) tbl.getValueAt(0, 5),
                    (Number) tbl.getValueAt(1, 5));

            if (res == null || res.getCode() != 200) {
                JOptionPane.showMessageDialog(this, "Lỗi khi kiểm tra khả năng phòng: " + (res != null ? res.getMessage() : "Không có phản hồi"), "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;

            }

            CheckRoomCapacityResponse rs = (CheckRoomCapacityResponse) res.getData();

            int leftoverAdults = rs.getLeftoverAdults();
            int leftoverChildren = rs.getLeftoverChildren();
            int leftoverTotal = leftoverAdults + leftoverChildren;

            String message;

            if (leftoverTotal == 0) {
                message = "Tất cả khách đã được xếp phòng hợp lý.";
                lblMessage.setForeground(new Color(0, 128, 0)); // màu xanh
            } else {
                if (leftoverChildren > 0) {
                    message = "Số khách chưa được xếp: " + leftoverTotal +
                            " (Người lớn: " + leftoverAdults +
                            ", Trẻ em: " + leftoverChildren + ")";
                } else {
                    message = "Số khách chưa được xếp: " + leftoverTotal +
                            " (Người lớn: " + leftoverAdults + ")";
                }

                lblMessage.setForeground(Color.RED);
            }

            lblMessage.setText(message);
            lblTotalRoom.setText(getTotalPriceRoom((Number) tbl.getValueAt(0, 3), (Number) tbl.getValueAt(1, 3)));
        });
        return true;
    }

    public String getTotalPriceRoom(Number priceSingle, Number priceDouble) {
        Long totalPrice = priceSingle.longValue() + priceDouble.longValue();
        return Constants.VND_FORMAT.format(totalPrice);

    }

    public java.util.List<RoomSelection> getSelectedRoom(java.util.List<RoomViewDTO> availableRooms) {

        int countSingleRoom = tbl.getValueAt(0, 5) != null ? ((Number) tbl.getValueAt(0, 5)).intValue() : 0;
        int countDoubleRoom = tbl.getValueAt(1, 5) != null ? ((Number) tbl.getValueAt(1, 5)).intValue() : 0;

        java.util.List<RoomSelection> selectedRooms = new java.util.ArrayList<>();


        for (RoomViewDTO room : availableRooms) {
            if (room.getRoomType().getRoomTypeId().equals("SINGLE") && countSingleRoom > 0) {
                selectedRooms.add(new RoomSelection(room.getRoomId(), room.getRoomNumber(), room.getRoomType().getRoomTypeId()));
                countSingleRoom--;
            } else if (room.getRoomType().getRoomTypeId().equals("DOUBLE") && countDoubleRoom > 0) {
                selectedRooms.add(new RoomSelection(room.getRoomId(), room.getRoomNumber(), room.getRoomType().getRoomTypeId()));
                countDoubleRoom--;
            }
            if (countSingleRoom == 0 && countDoubleRoom == 0) {
                break;
            }
        }
        return selectedRooms;
    }


    public void reset() {
        lblMessage.setText("Số khách chưa được xếp");
        lblMessage.setForeground(new Color(255, 0, 0));
        lblTotalRoom.setText("");
        var model = (CustomTable.CustomTableModel) tbl.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            model.setValueAt(0, i, 5); // reset số lượng đã chọn về 0
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Button btnNext;
    private Button btnPrev;
    private JLabel lbl;
    private JLabel lbl1;
    private JLabel lbl2;
    private JLabel lblMessage;
    private JLabel lblTotalRoom;
    private JPanel pnl1;
    private JScrollPane scr;
    private CustomTable tbl;
    // End of variables declaration//GEN-END:variables
}
