/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.booking2;

import iuh.fit.se.group1.dto.AmenityDTO;
import iuh.fit.se.group1.network.Response;
import iuh.fit.se.group1.network.client.SocketFacade;
import iuh.fit.se.group1.network.client.service.AmenityServiceClient;
import iuh.fit.se.group1.ui.component.custom.Button;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/**
 * @author THIS PC
 */
public class MainFlow3 extends JPanel {

    private final AmenityServiceClient amenityService = SocketFacade.getInstance().getAmenity();

    public List<AmenityDTO> fetchData() {
        try {
            Response response = amenityService.getAllAmenities();
            if (response.getCode() != 200) {
                JOptionPane.showMessageDialog(this, "Server returned HTTP Status " + response.getCode());
                return null;
            }
            return (List<AmenityDTO>) response.getData();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Creates new form MainFlow3
     */
    public MainFlow3() {
        initComponents();

        var model = (CustomTable2.CustomTable2Model) tbl.getModel();
        model.clear();

        fetchData().forEach(amenity ->
                model.addRow(new Object[]{
                        false,
                        amenity,
                        amenity.getPrice(),
                        0
                })
        );

        tbl.setQuantityChangeListener((r, newQuantity) -> {
            if (newQuantity > 0) {
                model.setValueAt(true, r, 0);
            }
            if (newQuantity == 0) {
                model.setValueAt(false, r, 0);
            }
        });
    }

    public List<AmenityDTO> getSelectedAmenities() {
        List<AmenityDTO> selectedAmenities = new ArrayList<>();
        var model = (CustomTable2.CustomTable2Model) tbl.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            Boolean isSelected = (Boolean) model.getValueAt(i, 0);
            if (isSelected != null && isSelected) {
                AmenityDTO amenityDTO = (AmenityDTO) model.getValueAt(i, 1);
                amenityDTO.setQuantity(model.getValueAt(i, 3) != null ? (Integer) model.getValueAt(i, 3) : 0);
                selectedAmenities.add(amenityDTO);
            }
        }
        return selectedAmenities;
    }


    public Button getBtnNext() {
        return btnNext;
    }

    public void setBtnNext(Button btnNext) {
        this.btnNext = btnNext;
    }

    public Button getBtnPrev() {
        return btnPrev;
    }

    public void setBtnPrev(Button btnPrev) {
        this.btnPrev = btnPrev;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNext = new Button();
        btnPrev = new Button();
        pnl1 = new JPanel();
        lbl1 = new JLabel();
        lbl2 = new JLabel();
        scr = new JScrollPane();
        tbl = new CustomTable2();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        btnNext.setBackground(new java.awt.Color(77, 134, 168));
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("TIẾP THEO");
        btnNext.setBorderRadius(5);
        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnPrev.setBackground(new java.awt.Color(227, 227, 227));
        btnPrev.setForeground(new java.awt.Color(77, 134, 168));
        btnPrev.setText("QUAY LẠI");
        btnPrev.setBorderRadius(5);
        btnPrev.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        pnl1.setBackground(new java.awt.Color(185, 215, 254));

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 0, 0));
        lbl1.setText("Dịch vụ đi kèm");

        lbl2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl2.setForeground(new java.awt.Color(0, 0, 0));
        lbl2.setText("Chọn thêm dịch vụ để nâng cao trải nghiệm");

        GroupLayout pnl1Layout = new GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
                pnl1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(pnl1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(pnl1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl1, GroupLayout.PREFERRED_SIZE, 342, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl2, GroupLayout.PREFERRED_SIZE, 741, GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl1Layout.setVerticalGroup(
                pnl1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(pnl1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lbl1)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl2)
                                .addContainerGap(39, Short.MAX_VALUE))
        );

        tbl.setForeground(new java.awt.Color(255, 255, 255));
        scr.setViewportView(tbl);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(scr, GroupLayout.Alignment.LEADING)
                                        .addComponent(pnl1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnPrev, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnNext, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)))
                                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(pnl1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(scr, GroupLayout.PREFERRED_SIZE, 281, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnNext, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnPrev, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents


    public void reset() {
        var model = (CustomTable2.CustomTable2Model) tbl.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            model.setValueAt(false, i, 0);
            model.setValueAt(0, i, 3);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Button btnNext;
    private Button btnPrev;
    private JLabel lbl1;
    private JLabel lbl2;
    private JPanel pnl1;
    private JScrollPane scr;
    private CustomTable2 tbl;
    // End of variables declaration//GEN-END:variables
}
