/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.booking2;

import iuh.fit.se.group1.dto.CustomerDTO;
import iuh.fit.se.group1.network.Response;
import iuh.fit.se.group1.network.client.SocketFacade;
import iuh.fit.se.group1.network.client.service.CustomerServiceClient;
import iuh.fit.se.group1.ui.component.custom.Button;
import iuh.fit.se.group1.ui.component.custom.TextField;
import iuh.fit.se.group1.ui.component.custom.message.CustomDialog;

import javax.swing.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.ResolverStyle;

/**
 * @author THIS PC
 */
public class MainFlow4 extends JPanel {
    public TextField getTxtDob() {
        return txtDob;
    }

    public void setTxtDob(TextField txtDob) {
        this.txtDob = txtDob;
    }

    public Button getBtnNext() {
        return btnNext;
    }

    public void setBtnNext(Button btnNext) {
        this.btnNext = btnNext;
    }

    public Button getBtnPrev() {
        return btnPrev;
    }

    public void setBtnPrev(Button btnPrev) {
        this.btnPrev = btnPrev;
    }

    /**
     * Creates new form MainFlow4
     */
    public MainFlow4() {
        initComponents();
    }

    private final CustomerServiceClient customerService = SocketFacade.getInstance().getCustomer();

    public boolean validateInput() {

        String citizenIdOrPassport = txtCitizenIdOrPassport.getText().trim();
        String fullName = txtFullName.getText().trim();
        String email = txtEmail.getText().trim();
        String phone = txtPhone.getText().trim();

        // Validate CMND/CCCD hoặc Passport
        if (citizenIdOrPassport.isEmpty()) {
            showError("CCCD/Passport không được để trống!", 400, 200);
            return false;
        }

        // CCCD Việt Nam: 12 số hoặc 9 số (CMND cũ)
        String regexCCCD = "^(\\d{12})$";
        // Passport quốc tế: 1 chữ cái + 7 số (phổ biến VN: B1234567)
        String regexPassport = "^[A-Za-z][0-9]{7,8}$";

        if (!citizenIdOrPassport.matches(regexCCCD) &&
                !citizenIdOrPassport.matches(regexPassport)) {
            showError("CCCD/Passport không hợp lệ!", 500, 200);
            return false;
        }

        // Validate tên
        if (fullName.isEmpty()) {
            showError("Họ tên không được để trống!", 500, 200);
            return false;
        }

        // Tên chỉ gồm chữ + khoảng trắng, không số, không ký tự đặc biệt
        if (!fullName.matches("^(\\p{L}{2,})(\\s+\\p{L}{2,})+$")) {
            showError("Tên phải gồm ít nhất 2 từ, mỗi từ từ 2 ký tự trở lên và không chứa số/ký tự đặc biệt!", 700, 200);
            return false;
        }


        // Validate email (nếu không rỗng)
        // Validate email (nếu không rỗng)
        if (!email.isEmpty()) {
            String regexEmail = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
            if (!email.matches(regexEmail)) {
                showError("Email không hợp lệ!", 500, 200);
                return false;
            }
        }


        // Validate số điện thoại VN
        // VN: 10 số, bắt đầu bằng 0
        String regexPhone = "^0\\d{9}$";
        if (!phone.matches(regexPhone)) {
            showError("Số điện thoại không hợp lệ!", 500, 200);
            return false;
        }

        return true;
    }

    public static String formatName(String name) {
        if (name == null || name.trim().isEmpty()) {
            return "";
        }

        // Xóa khoảng trắng dư
        name = name.trim().replaceAll("\\s+", " ");

        StringBuilder result = new StringBuilder();

        for (String word : name.split(" ")) {
            if (!word.isEmpty()) {
                String first = word.substring(0, 1).toUpperCase();
                String rest = word.substring(1).toLowerCase();
                result.append(first).append(rest).append(" ");
            }
        }

        return result.toString().trim();
    }

    private void showError(String s, int w, int h) {
        CustomDialog.showMessage(null, s, "Giá trị nhập không hợp lệ", CustomDialog.MessageType.ERROR, w, h);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrev = new Button();
        btnNext = new Button();
        pnl = new JPanel();
        lbl1 = new JLabel();
        lbl2 = new JLabel();
        lbl3 = new JLabel();
        txtCitizenIdOrPassport = new TextField();
        lbll4 = new JLabel();
        txtFullName = new TextField();
        lbl5 = new JLabel();
        txtEmail = new TextField();
        llbl6 = new JLabel();
        txtPhone = new TextField();
        txtDob = new TextField();
        lbl7 = new JLabel();
        rdoGender = new GenderRadioButtons();

        setBackground(new java.awt.Color(255, 255, 255));

        btnPrev.setBackground(new java.awt.Color(227, 227, 227));
        btnPrev.setForeground(new java.awt.Color(77, 134, 168));
        btnPrev.setText("QUAY LẠI");
        btnPrev.setBorderRadius(5);
        btnPrev.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnNext.setBackground(new java.awt.Color(77, 134, 168));
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("TIẾP THEO");
        btnNext.setBorderRadius(5);
        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        pnl.setBackground(new java.awt.Color(185, 215, 254));

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 0, 0));
        lbl1.setText("Nhập thông tin khách hàng");

        lbl2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl2.setForeground(new java.awt.Color(0, 0, 0));
        lbl2.setText("Vui lòng nhập thông tin chính xác ");

        GroupLayout pnlLayout = new GroupLayout(pnl);
        pnl.setLayout(pnlLayout);
        pnlLayout.setHorizontalGroup(
                pnlLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(pnlLayout.createSequentialGroup()
                                .addContainerGap(30, Short.MAX_VALUE)
                                .addGroup(pnlLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl1, GroupLayout.PREFERRED_SIZE, 342, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl2, GroupLayout.PREFERRED_SIZE, 741, GroupLayout.PREFERRED_SIZE)))
        );
        pnlLayout.setVerticalGroup(
                pnlLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(pnlLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lbl1)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl2)
                                .addContainerGap(18, Short.MAX_VALUE))
        );

        lbl3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbl3.setForeground(new java.awt.Color(0, 0, 0));
        lbl3.setText("CCCD/Hộ chiếu:");

        txtCitizenIdOrPassport.setForeground(new java.awt.Color(0, 0, 0));
        txtCitizenIdOrPassport.setBorderColor(new java.awt.Color(102, 102, 102));
        txtCitizenIdOrPassport.setBorderRadius(5);
        txtCitizenIdOrPassport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    txtCitizenIdOrPassportActionPerformed(evt);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }
        });

        lbll4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbll4.setForeground(new java.awt.Color(0, 0, 0));
        lbll4.setText("Họ và tên:");

        txtFullName.setForeground(new java.awt.Color(0, 0, 0));
        txtFullName.setBorderColor(new java.awt.Color(102, 102, 102));
        txtFullName.setBorderRadius(5);
        txtFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullNameActionPerformed(evt);
            }
        });

        lbl5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbl5.setForeground(new java.awt.Color(0, 0, 0));
        lbl5.setText("Email:");

        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.setBorderColor(new java.awt.Color(102, 102, 102));
        txtEmail.setBorderRadius(5);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        llbl6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        llbl6.setForeground(new java.awt.Color(0, 0, 0));
        llbl6.setText("Số điện thoại:");

        txtPhone.setForeground(new java.awt.Color(0, 0, 0));
        txtPhone.setBorderColor(new java.awt.Color(102, 102, 102));
        txtPhone.setBorderRadius(5);
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });

        txtDob.setForeground(new java.awt.Color(0, 0, 0));
        txtDob.setBorderColor(new java.awt.Color(102, 102, 102));
        txtDob.setBorderRadius(5);
        txtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDobActionPerformed(evt);
            }
        });

        lbl7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbl7.setForeground(new java.awt.Color(0, 0, 0));
        lbl7.setText("Ngày sinh");

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnPrev, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnNext, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lbl7, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtDob, GroupLayout.PREFERRED_SIZE, 242, GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(rdoGender, GroupLayout.PREFERRED_SIZE, 241, GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(llbl6, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtPhone, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addComponent(pnl, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(lbl5, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtEmail, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(lbl3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(lbll4, GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(txtFullName, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(txtCitizenIdOrPassport, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                                .addContainerGap(43, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(pnl, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl3, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCitizenIdOrPassport, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbll4, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFullName, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl5, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEmail, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(llbl6, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPhone, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(rdoGender, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtDob, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lbl7, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnPrev, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnNext, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCitizenIdOrPassportActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_txtCitizenIdOrPassportActionPerformed

        String citizenId = txtCitizenIdOrPassport.getText().trim();

        Response response = customerService.getCustomerByCitizenId(citizenId);

        if (response == null || response.getCode() != 200) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tìm kiếm khách hàng: " + response.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        CustomerDTO existingCustomer = (CustomerDTO) response.getData();
        if (existingCustomer != null) {
            txtFullName.setText(existingCustomer.getFullName());
            txtEmail.setText(existingCustomer.getEmail());
            txtPhone.setText(existingCustomer.getPhone());

            DateTimeFormatter outputFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            String dobStr = existingCustomer.getDateOfBirth().format(outputFormat);
            txtDob.setText(dobStr);

            rdoGender.setSelectedGender(!existingCustomer.isGender());
            txtDob.requestFocus();
            return;
        }
        txtFullName.requestFocus();
    }//GEN-LAST:event_txtCitizenIdOrPassportActionPerformed

    private void txtFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullNameActionPerformed
        txtFullName.setText(formatName(txtFullName.getText()));

        txtEmail.requestFocus();
    }//GEN-LAST:event_txtFullNameActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        txtPhone.requestFocus();
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        txtDob.requestFocus();
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDobActionPerformed
    }//GEN-LAST:event_txtDobActionPerformed

    public boolean setupDob() {
        DateTimeFormatter inputFormat = DateTimeFormatter.ofPattern("ddMMyyyy");
        DateTimeFormatter outputFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String dob = txtDob.getText().trim();

        if (!validateDate(dob)) {
            return false;
        }

        if (dob.contains("/")) {
            dob = dob.replace("/", "");
        }


        LocalDate date = LocalDate.parse(dob, inputFormat);
        String rs = date.format(outputFormat);

        txtDob.setText(rs);
        return true;
    }

    public boolean validateDate(String date) {

        if (date == null || date.trim().isEmpty()) {
            showError("Ngày sinh không được để trống!", 500, 200);
            return false;
        }

        date = date.trim();

        // Nếu có dấu "/", bỏ để thành ddMMyyyy
        if (date.contains("/")) {
            date = date.replace("/", "");
        }

        if (!date.matches("\\d{8}")) {
            showError("Định dạng ngày sinh không hợp lệ (ddMMyyyy hoặc dd/MM/yyyy)!", 550, 200);
            return false;
        }

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("ddMMyyyy")
                .withResolverStyle(ResolverStyle.SMART);

        try {
            LocalDate dob = LocalDate.parse(date, formatter);

            if (dob.isAfter(LocalDate.now())) {
                showError("Ngày sinh không được ở tương lai!", 500, 200);
                return false;
            }

            if (dob.isBefore(LocalDate.now().minusYears(150))) {
                showError("Ngày sinh không hợp lệ (quá xa trong quá khứ)!", 500, 200);
                return false;
            }

            // ⭐️ Kiểm tra phải >= 18 tuổi
            if (dob.isAfter(LocalDate.now().minusYears(18))) {
                showError("Khách hàng phải từ 18 tuổi trở lên!", 500, 200);
                return false;
            }

        } catch (Exception e) {
            showError("Ngày sinh không hợp lệ!", 500, 200);
            return false;
        }
        return true;
    }


    public CustomerDTO getCustomer() {
        try {
            String citizenIdOrPassport = txtCitizenIdOrPassport.getText().trim();
            String fullName = txtFullName.getText().trim();
            String email = txtEmail.getText().trim();
            String phone = txtPhone.getText().trim();
            Response response = customerService.getCustomerByCitizenId(citizenIdOrPassport);

            if (response == null || response.getCode() != 200) {
                JOptionPane.showMessageDialog(this, "Lỗi khi tìm kiếm khách hàng: " + response.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                return null;
            }

            CustomerDTO customerSaveDB = (CustomerDTO) response.getData();

            if (customerSaveDB != null) {
                boolean needUpdate = false;

                txtFullName.setText(customerSaveDB.getFullName());
                txtEmail.setText(customerSaveDB.getEmail());
                txtPhone.setText(customerSaveDB.getPhone());
                DateTimeFormatter outputFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                String dobStr = customerSaveDB.getDateOfBirth().format(outputFormat);
                txtDob.setText(dobStr);

                if (!customerSaveDB.getEmail().equals(email)) {
                    customerSaveDB.setEmail(email);
                    needUpdate = true;
                }

                if (!customerSaveDB.getPhone().equals(phone)) {
                    customerSaveDB.setPhone(phone);
                    needUpdate = true;
                }

                if (needUpdate) {
                    response = customerService.updateCustomer(customerSaveDB);
                    if (response == null || response.getCode() != 200) {
                        JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật thông tin khách hàng: " + response.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                        return null;
                    }
                    return (CustomerDTO) response.getData();
                }
                return customerSaveDB;
            }

            // Nếu chưa có trong DB → tạo mới
            CustomerDTO customer = new CustomerDTO();
            customer.setCitizenId(citizenIdOrPassport);
            customer.setFullName(formatName(fullName));
            customer.setEmail(email);
            customer.setPhone(phone);

            DateTimeFormatter inputFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate dob = LocalDate.parse(txtDob.getText().trim(), inputFormat);

            customer.setDateOfBirth(dob);
            customer.setGender(rdoGender.getSelectedGender());

            return customer;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi xử lý thông tin khách hàng: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }


    public void reset() {
        txtCitizenIdOrPassport.setText("");
        txtFullName.setText("");
        txtEmail.setText("");
        txtPhone.setText("");
        txtDob.setText("");
        rdoGender.setSelectedGender(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Button btnNext;
    private Button btnPrev;
    private JLabel lbl1;
    private JLabel lbl2;
    private JLabel lbl3;
    private JLabel lbl5;
    private JLabel lbl7;
    private JLabel lbll4;
    private JLabel llbl6;
    private JPanel pnl;
    private GenderRadioButtons rdoGender;
    private TextField txtCitizenIdOrPassport;
    private TextField txtDob;
    private TextField txtEmail;
    private TextField txtFullName;
    private TextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
