/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.booking2;


import javax.swing.*;
import java.awt.*;

/**
 *
 * @author THIS PC
 */
public class SequenceBooking extends JPanel {

    /**
     * Creates new form SequenceBooking
     */
    public SequenceBooking() {
        initComponents();
        setBorder(BorderFactory.createCompoundBorder(
                new RoundedBorder(18),
                BorderFactory.createEmptyBorder(5, 5, 5, 5)
        ));

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new JSeparator();
        jSeparator2 = new JSeparator();
        jSeparator3 = new JSeparator();
        jSeparator5 = new JSeparator();
        lbl1 = new JLabel();
        lbl2 = new JLabel();
        lbl3 = new JLabel();
        lbl4 = new JLabel();
        lbl5 = new JLabel();
        circleNumber2 = new CircleNumber();
        circleNumber5 = new CircleNumber();
        circleNumber4 = new CircleNumber();
        circleNumber3 = new CircleNumber();
        circleNumber1 = new CircleNumber();

        setBackground(new Color(255, 255, 255));

        lbl1.setBackground(new Color(105, 105, 105));
        lbl1.setForeground(new Color(105, 105, 105));
        lbl1.setHorizontalAlignment(SwingConstants.CENTER);
        lbl1.setText("Nhu cầu");

        lbl2.setForeground(new Color(105, 105, 105));
        lbl2.setHorizontalAlignment(SwingConstants.CENTER);
        lbl2.setText("Chọn phòng");

        lbl3.setForeground(new Color(105, 105, 105));
        lbl3.setHorizontalAlignment(SwingConstants.CENTER);
        lbl3.setText("Dịch vụ");

        lbl4.setForeground(new Color(105, 105, 105));
        lbl4.setHorizontalAlignment(SwingConstants.CENTER);
        lbl4.setText("Thông tin");

        lbl5.setFont(new Font("Segoe UI", 0, 13)); // NOI18N
        lbl5.setForeground(new Color(105, 105, 105));
        lbl5.setHorizontalAlignment(SwingConstants.CENTER);
        lbl5.setText("Xác nhận");

        circleNumber2.setNumber("2");

        GroupLayout circleNumber2Layout = new GroupLayout(circleNumber2);
        circleNumber2.setLayout(circleNumber2Layout);
        circleNumber2Layout.setHorizontalGroup(
            circleNumber2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        circleNumber2Layout.setVerticalGroup(
            circleNumber2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        circleNumber5.setNumber("5");

        GroupLayout circleNumber5Layout = new GroupLayout(circleNumber5);
        circleNumber5.setLayout(circleNumber5Layout);
        circleNumber5Layout.setHorizontalGroup(
            circleNumber5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        circleNumber5Layout.setVerticalGroup(
            circleNumber5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        circleNumber4.setNumber("4");

        GroupLayout circleNumber4Layout = new GroupLayout(circleNumber4);
        circleNumber4.setLayout(circleNumber4Layout);
        circleNumber4Layout.setHorizontalGroup(
            circleNumber4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        circleNumber4Layout.setVerticalGroup(
            circleNumber4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        circleNumber3.setNumber("3");

        GroupLayout circleNumber3Layout = new GroupLayout(circleNumber3);
        circleNumber3.setLayout(circleNumber3Layout);
        circleNumber3Layout.setHorizontalGroup(
            circleNumber3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        circleNumber3Layout.setVerticalGroup(
            circleNumber3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        GroupLayout circleNumber1Layout = new GroupLayout(circleNumber1);
        circleNumber1.setLayout(circleNumber1Layout);
        circleNumber1Layout.setHorizontalGroup(
            circleNumber1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        circleNumber1Layout.setVerticalGroup(
            circleNumber1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(circleNumber1, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(circleNumber2, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(circleNumber3, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(circleNumber4, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(circleNumber5, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lbl1, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(lbl2, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(lbl3, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(lbl4, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(lbl5, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(circleNumber1, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(circleNumber2, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(circleNumber3, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(circleNumber4, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(circleNumber5, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 12, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jSeparator5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, 18, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)))))
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbl2)
                    .addComponent(lbl1)
                    .addComponent(lbl3)
                    .addComponent(lbl5)
                    .addComponent(lbl4))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    /**
     * Thiết lập step đang active (0 → 4)
     * @param step step cần active
     */
    public void setActiveStep(int step) {
        JLabel[] labels = { lbl1, lbl2, lbl3, lbl4, lbl5 };
        CircleNumber[] circles = {
                circleNumber1,
                circleNumber2,
                circleNumber3,
                circleNumber4,
                circleNumber5
        };

        Color activeColor = new Color(77, 134, 168);
        Color inactiveColor = new Color(105, 105, 105);

        if (step < 0 || step >= labels.length) {
            return;
        }

        // Reset toàn bộ
        for (int i = 0; i < labels.length; i++) {
            labels[i].setForeground(inactiveColor);
            circles[i].setActive(false);
        }



        for (int i = 0; i <= step; i++) {
            labels[i].setForeground(activeColor);
            circles[i].setActive(true);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CircleNumber circleNumber1;
    private CircleNumber circleNumber2;
    private CircleNumber circleNumber3;
    private CircleNumber circleNumber4;
    private CircleNumber circleNumber5;
    private JSeparator jSeparator1;
    private JSeparator jSeparator2;
    private JSeparator jSeparator3;
    private JSeparator jSeparator5;
    private JLabel lbl1;
    private JLabel lbl2;
    private JLabel lbl3;
    private JLabel lbl4;
    private JLabel lbl5;
    // End of variables declaration//GEN-END:variables
}
