/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.paymentv2;


import iuh.fit.se.group1.ui.component.booking2.CircleNumber;
import iuh.fit.se.group1.ui.component.booking2.RoundedBorder;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author THIS PC
 */
public class SequencePayment extends JPanel {

    /**
     * Creates new form SequenceBooking
     */
    public SequencePayment() {
        initComponents();
        setBorder(BorderFactory.createCompoundBorder(
                new RoundedBorder(18),
                BorderFactory.createEmptyBorder(5, 5, 5, 5)
        ));

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spn1 = new JSeparator();
        lbl1 = new JLabel();
        lbl2 = new JLabel();
        lbl3 = new JLabel();
        circleNumber2 = new CircleNumber();
        circleNumber3 = new CircleNumber();
        circleNumber1 = new CircleNumber();
        spn2 = new JSeparator();

        setBackground(new Color(255, 255, 255));

        lbl1.setBackground(new Color(105, 105, 105));
        lbl1.setForeground(new Color(105, 105, 105));
        lbl1.setHorizontalAlignment(SwingConstants.CENTER);
        lbl1.setText("Chọn phòng");

        lbl2.setForeground(new Color(105, 105, 105));
        lbl2.setHorizontalAlignment(SwingConstants.CENTER);
        lbl2.setText("Xác nhận thông tin");

        lbl3.setForeground(new Color(105, 105, 105));
        lbl3.setHorizontalAlignment(SwingConstants.CENTER);
        lbl3.setText("Thanh toán");

        circleNumber2.setNumber("2");

        GroupLayout circleNumber2Layout = new GroupLayout(circleNumber2);
        circleNumber2.setLayout(circleNumber2Layout);
        circleNumber2Layout.setHorizontalGroup(
            circleNumber2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        circleNumber2Layout.setVerticalGroup(
            circleNumber2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        circleNumber3.setNumber("3");

        GroupLayout circleNumber3Layout = new GroupLayout(circleNumber3);
        circleNumber3.setLayout(circleNumber3Layout);
        circleNumber3Layout.setHorizontalGroup(
            circleNumber3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        circleNumber3Layout.setVerticalGroup(
            circleNumber3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        GroupLayout circleNumber1Layout = new GroupLayout(circleNumber1);
        circleNumber1.setLayout(circleNumber1Layout);
        circleNumber1Layout.setHorizontalGroup(
            circleNumber1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        circleNumber1Layout.setVerticalGroup(
            circleNumber1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(circleNumber1, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spn1, GroupLayout.PREFERRED_SIZE, 175, GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(circleNumber2, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(spn2, GroupLayout.PREFERRED_SIZE, 163, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(circleNumber3, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl1, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141)
                        .addComponent(lbl2, GroupLayout.PREFERRED_SIZE, 129, GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(lbl3, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(circleNumber1, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)
                        .addComponent(circleNumber2, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)
                        .addComponent(circleNumber3, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(spn1, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 12, GroupLayout.PREFERRED_SIZE)
                            .addComponent(spn2, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 12, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );
    }// </editor-fold>//GEN-END:initComponents


    /**
     * Thiết lập step đang active (0 → 4)
     * @param step step cần active
     */
    public void setActiveStep(int step) {
        JLabel[] labels = { lbl1, lbl2, lbl3,};
        CircleNumber[] circles = {
                circleNumber1,
                circleNumber2,
                circleNumber3,
        };

        Color activeColor = new Color(77, 134, 168);
        Color inactiveColor = new Color(105, 105, 105);

        if (step < 0 || step >= labels.length) {
            return;
        }

        // Reset toàn bộ
        for (int i = 0; i < labels.length; i++) {
            labels[i].setForeground(inactiveColor);
            circles[i].setActive(false);
        }



        for (int i = 0; i <= step; i++) {
            labels[i].setForeground(activeColor);
            circles[i].setActive(true);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CircleNumber circleNumber1;
    private CircleNumber circleNumber2;
    private CircleNumber circleNumber3;
    private JLabel lbl1;
    private JLabel lbl2;
    private JLabel lbl3;
    private JSeparator spn1;
    private JSeparator spn2;
    // End of variables declaration//GEN-END:variables
}
