/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.custom.date;

import iuh.fit.se.group1.enums.BookingType;
import raven.glasspanepopup.GlassPanePopup;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author THIS PC
 */
public class DateTimePicker extends JPanel {

    private Calendar cal = Calendar.getInstance();

    /**
     * Creates new form DateTimePicker
     */
    public DateTimePicker() {
        initComponents();
        header1.getLblMonthAndYear().setText(convertTitle(cal.get(Calendar.MONTH)+1,cal.get(Calendar.YEAR)));
        calendarUI1.setCalendar(cal);
        header1.getBtnNext().addActionListener(e -> {
            cal.add(Calendar.MONTH, 1);
            header1.getLblMonthAndYear().setText(convertTitle(cal.get(Calendar.MONTH)+1,cal.get(Calendar.YEAR)));
            calendarUI1.setCalendar(cal);

        });
        header1.getBtnPrev().addActionListener(e -> {
            cal.add(Calendar.MONTH, -1);
            header1.getLblMonthAndYear().setText(convertTitle(cal.get(Calendar.MONTH)+1,cal.get(Calendar.YEAR)));
            calendarUI1.setCalendar(cal);
        });
        timePicker1.getBtnCancel().addActionListener(e-> closePicker());
        timePicker1.getBtnNow().addActionListener(e-> setNow());
    }

    private String convertTitle(int month,int year){
        return String.format("Tháng %d - %d",month,year);
    }

    private void setNow() {
        this.cal = Calendar.getInstance();
        calendarUI1.setCalendar(Calendar.getInstance());
        header1.getLblMonthAndYear().setText(convertTitle(cal.get(Calendar.MONTH)+1,cal.get(Calendar.YEAR)));
        timePicker1.setTime(cal.get(Calendar.HOUR_OF_DAY),cal.get(Calendar.MINUTE));

    }

    public static void attachTo(JTextField textField, JComboBox<String> bookingType, Runnable onSelected ){
        textField.setEditable(false);

        Calendar now = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy HH:mm");
        textField.setText(sdf.format(now.getTime()));
        textField.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DateTimePicker picker = new DateTimePicker();

                BookingType bookingTypeValue = BookingType.fromIndex(bookingType.getSelectedIndex());

                picker.timePicker1.setVisibleTimePicker(BookingType.HOURLY.equals(bookingTypeValue));

                GlassPanePopup.showPopup(picker);
                picker.confirm(e -> {
                    textField.setText(String.format("%02d-%02d-%d %02d:%02d",
                            picker.cal.get(Calendar.DAY_OF_MONTH),
                            picker.cal.get(Calendar.MONTH) + 1,
                            picker.cal.get(Calendar.YEAR),
                            picker.timePicker1.getHour(),
                            picker.timePicker1.getMinute()
                    ));
                    picker.closePicker();
                    // Cần thực hiện 1 function từ ngoài truyền vào
                    if (onSelected != null) onSelected.run();
                });
            }
        });
    }

    private void closePicker() {
        GlassPanePopup.closePopupLast();
    }

    public void confirm(ActionListener l){
        timePicker1.getBtnConfirm().addActionListener(l);
    }


    public TimePicker getTimePicker1() {
        return timePicker1;
    }

    public void setTimePicker1(TimePicker timePicker1) {
        this.timePicker1 = timePicker1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calendarUI1 = new CalendarUI();
        header1 = new Header();
        timePicker1 = new TimePicker();

        setBackground(new Color(255, 255, 255));

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(header1, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(calendarUI1, GroupLayout.PREFERRED_SIZE, 352, GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addComponent(timePicker1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(calendarUI1, GroupLayout.PREFERRED_SIZE, 223, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(timePicker1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CalendarUI calendarUI1;
    private Header header1;
    private TimePicker timePicker1;
    // End of variables declaration//GEN-END:variables
}
