/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.custom.date;

import iuh.fit.se.group1.ui.component.custom.Button;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author THIS PC
 */
public class Header extends javax.swing.JPanel {

    /**
     * Creates new form Header
     */
    public Header() {
        initComponents();
        btnNext.setIcon(FontIcon.of(FontAwesomeSolid.ARROW_RIGHT,20,new Color(105, 165, 200)));
        btnPrev.setIcon(FontIcon.of(FontAwesomeSolid.ARROW_LEFT,20,new Color(105, 165, 200)));
    }

    public JButton getBtnNext() {
        return btnNext;
    }

    public void setBtnNext(Button btnNext) {
        this.btnNext = btnNext;
    }

    public JButton getBtnPrev() {
        return btnPrev;
    }

    public void setBtnPrev(Button btnPrev) {
        this.btnPrev = btnPrev;
    }

    public JLabel getLblMonthAndYear() {
        return lblMonthAndYear;
    }

    public void setLblMonthAndYear(JLabel lblMonthAndYear) {
        this.lblMonthAndYear = lblMonthAndYear;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMonthAndYear = new JLabel();
        btnNext = new Button();
        btnPrev = new Button();

        setBackground(new Color(255, 255, 255));

        lblMonthAndYear.setBackground(new Color(0, 0, 0));
        lblMonthAndYear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMonthAndYear.setForeground(new Color(0, 0, 0));
        lblMonthAndYear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMonthAndYear.setText(" Tháng 11 2025");

        btnNext.setBackground(new Color(255, 255, 255));
        btnNext.setText("");

        btnPrev.setBackground(new Color(255, 255, 255));
        btnPrev.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMonthAndYear, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMonthAndYear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Button btnNext;
    private Button btnPrev;
    private JLabel lblMonthAndYear;
    // End of variables declaration//GEN-END:variables
}
