/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.custom.date;

import iuh.fit.se.group1.ui.component.custom.Button;

import javax.swing.*;
import java.time.LocalTime;

/**
 *
 * @author THIS PC
 */
public class TimePicker extends javax.swing.JPanel {

    /**
     * Creates new form TimePicker
     */
    public TimePicker() {
        initComponents();
        
        //todo:sua lai gioi han
        setTime(LocalTime.now().getHour(), LocalTime.now().getMinute());
    }

    public void setVisibleTimePicker (boolean visible) {
        jLabel1.setVisible(visible);
        jLabel2.setVisible(visible);
        jLabel3.setVisible(visible);
        spnMinute.setVisible(visible);
        spnHours.setVisible(visible);

    }

    public Button getBtnCancel() {
        return btnCancel;
    }

    public void setBtnCancel(Button btnCancel) {
        this.btnCancel = btnCancel;
    }

    public Button getBtnConfirm() {
        return btnConfirm;
    }

    public void setBtnConfirm(Button btnConfirm) {
        this.btnConfirm = btnConfirm;
    }

    public Button getBtnNow() {
        return btnNow;
    }

    public void setBtnNow(Button btnNow) {
        this.btnNow = btnNow;
    }

    public JSpinner getSpnHours() {
        return spnHours;
    }

    public void setSpnHours(JSpinner spnHours) {
        this.spnHours = spnHours;
    }

    public JSpinner getSpnMinute() {
        return spnMinute;
    }

    public void setSpnMinute(JSpinner spnMinute) {
        this.spnMinute = spnMinute;
    }

    public int getHour() {
        return (int) spnHours.getValue();
    }
    public int getMinute() {
        return (int) spnMinute.getValue();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private javax.swing.JPanel buttonPanel; // thêm dòng này vào phần khai báo biến

    @SuppressWarnings("unchecked")
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spnMinute = new JSpinner();
        spnHours = new JSpinner();
        btnNow = new Button();
        btnCancel = new Button();
        btnConfirm = new Button();
        buttonPanel = new javax.swing.JPanel(); // tạo panel chứa 3 nút

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Chọn giờ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Giờ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Phút");

        btnNow.setText("Bây giờ");
        btnNow.setBorderRadius(5);

        btnCancel.setBackground(new java.awt.Color(255, 0, 0));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Hủy");
        btnCancel.setBorderRadius(5);
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 12));

        btnConfirm.setBackground(new java.awt.Color(0, 255, 0));
        btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirm.setText("Xác nhận");
        btnConfirm.setBorderRadius(5);
        btnConfirm.setFont(new java.awt.Font("Segoe UI", 1, 12));

        // ✅ Gom 3 nút vào 1 panel con và căn giữa
        buttonPanel.setBackground(new java.awt.Color(255, 255, 255));
        javax.swing.GroupLayout buttonLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonLayout);
        buttonLayout.setHorizontalGroup(
                buttonLayout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addComponent(btnNow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20)
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE)
        );
        buttonLayout.setVerticalGroup(
                buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(spnHours, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(spnMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(buttonPanel))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createSequentialGroup()
                        .addGap(10)
                        .addComponent(jLabel1)
                        .addGap(10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(spnHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(spnMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10)
                        .addComponent(buttonPanel)
                        .addGap(10)
        );
    }

    public void setTime(int hour, int minute) {
        spnHours.setValue(hour);
        spnMinute.setValue(minute);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Button btnCancel;
    private Button btnConfirm;
    private Button btnNow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private JSpinner spnHours;
    private JSpinner spnMinute;
    // End of variables declaration//GEN-END:variables
}
