package iuh.fit.se.group1.ui.component.dashboard;

import iuh.fit.se.group1.enums.TimeType;
import iuh.fit.se.group1.ui.component.custom.Button;

import java.awt.event.MouseListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author THIS PC
 */
public class HeaderDashboard extends javax.swing.JPanel {

    /**
     * Creates new form HeaderDashboard
     */
    public HeaderDashboard() {
        initComponents();
        setActiveButton(TimeType.TODAY);
    }

    public Button getBtn30Days() {
        return btn30Days;
    }

    public void setBtn30Days(Button btn30Days) {
        this.btn30Days = btn30Days;
    }

    public Button getBtn7Days() {
        return btn7Days;
    }

    public void setBtn7Days(Button btn7Days) {
        this.btn7Days = btn7Days;
    }

    public Button getBtn90Days() {
        return btn90Days;
    }

    public void setBtn90Days(Button btn90Days) {
        this.btn90Days = btn90Days;
    }

    public Button getBtnToday() {
        return btnToday;
    }

    public void setBtnToday(Button btnToday) {
        this.btnToday = btnToday;
    }
    



    public void setAction(MouseListener l){
        btnToday.addMouseListener(l);
        btn7Days.addMouseListener(l);
        btn30Days.addMouseListener(l);
        btn90Days.addMouseListener(l);
    }

    public void setActiveButton(TimeType timeType) {
        // timeType: 1 - today, 2 - 7 days, 3 - 30 days, 4 - 90 days
        Button[] btns = {btnToday, btn7Days, btn30Days, btn90Days};
        for (int i = 0; i < btns.length; i++) {
            if (i == timeType.getValue()-1) {
                btns[i].setBackground(new java.awt.Color(0, 123, 255));
                btns[i].setForeground(new java.awt.Color(255, 255, 255));
            } else {
                btns[i].setBackground(new java.awt.Color(214,217,223));
                btns[i].setForeground(new java.awt.Color(0, 0, 0));
            }
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnToday = new Button();
        btn7Days = new Button();
        btn30Days = new Button();
        btn90Days = new Button();

        setBackground(new java.awt.Color(241, 241, 241));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Dashboard");

        btnToday.setText("Hôm này");
        btnToday.setBorderRadius(5);

        btn7Days.setText("7 Ngày");
        btn7Days.setBorderRadius(5);

        btn30Days.setText("30 Ngày");
        btn30Days.setBorderRadius(5);

        btn90Days.setText("90 Ngày");
        btn90Days.setBorderRadius(5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 552, Short.MAX_VALUE)
                .addComponent(btnToday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn7Days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn30Days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn90Days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn30Days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn90Days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7Days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Button btn30Days;
    private Button btn7Days;
    private Button btn90Days;
    private Button btnToday;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
