/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.dashboard;

import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;

import java.awt.*;

/**
 *
 * @author THIS PC
 */
public class PnlListCard extends javax.swing.JPanel {


    private static final Color ROM_OCCUPANCY_RATE_COLOR = new Color(50, 145, 255);
    private static final Color BOOKING_RATE_COLOR = new Color(255, 108, 3);
    private static final Color REVENUE_COLOR = new Color(239, 180, 46);
    private static final Color NUMBER_CHECKIN_COLOR = new Color(13,200, 7);

    /**
     * Creates new form PnlListCard
     */
    public PnlListCard() {
        initComponents();

        // Card 1: Phòng trống - có vòng tròn
        roomOccupancyRateCard.setTitle("Phòng trống");
        roomOccupancyRateCard.setBorderColor(ROM_OCCUPANCY_RATE_COLOR);
        roomOccupancyRateCard.setLblIconRate(FontIcon.of(FontAwesomeSolid.DOOR_OPEN,20,ROM_OCCUPANCY_RATE_COLOR));
        roomOccupancyRateCard.setColorCircularProgress(ROM_OCCUPANCY_RATE_COLOR);

        // Card 2: Tỷ lệ đặt phòng - KHÔNG có vòng tròn
        bookingRateCard.setTitle("Tỷ lệ đặt phòng");
        bookingRateCard.setBorderColor(BOOKING_RATE_COLOR);
        bookingRateCard.setLblIconRate(FontIcon.of(FontAwesomeSolid.CALENDAR_CHECK,20,BOOKING_RATE_COLOR));
        bookingRateCard.getCircularProgress1().setVisible(false);

        // Card 3: Doanh thu - KHÔNG có vòng tròn
        revenueCard.setTitle("Doanh thu");
        revenueCard.setBorderColor(REVENUE_COLOR);
        revenueCard.setLblIconRate(FontIcon.of(FontAwesomeSolid.COINS,20,REVENUE_COLOR));
        revenueCard.getCircularProgress1().setVisible(false);

        // Card 4: Số lượt check-in - KHÔNG có vòng tròn
        numberCheckInCard.setTitle("Số lượt check-in");
        numberCheckInCard.setBorderColor(NUMBER_CHECKIN_COLOR);
        numberCheckInCard.setLblIconRate(FontIcon.of(FontAwesomeSolid.MAP_MARKER_ALT,20,NUMBER_CHECKIN_COLOR));
        numberCheckInCard.getCircularProgress1().setVisible(false);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomOccupancyRateCard = new CardReport();
        bookingRateCard = new CardReport();
        revenueCard = new CardReport();
        numberCheckInCard = new CardReport();

        setBackground(new Color(241, 241, 241));
        setForeground(new Color(255, 255, 255));
        FlowLayout flowLayout1 = new FlowLayout(FlowLayout.CENTER, 30, 5);
        flowLayout1.setAlignOnBaseline(true);
        setLayout(flowLayout1);

        add(roomOccupancyRateCard);
        add(bookingRateCard);
        add(revenueCard);
        add(numberCheckInCard);
    }// </editor-fold>//GEN-END:initComponents

    public CardReport getBookingRateCard() {
        return bookingRateCard;
    }

    public void setBookingRateCard(CardReport bookingRateCard) {
        this.bookingRateCard = bookingRateCard;
    }

    public CardReport getNumberCheckInCard() {
        return numberCheckInCard;
    }

    public void setNumberCheckInCard(CardReport numberCheckInCard) {
        this.numberCheckInCard = numberCheckInCard;
    }

    public CardReport getRevenueCard() {
        return revenueCard;
    }

    public void setRevenueCard(CardReport revenueCard) {
        this.revenueCard = revenueCard;
    }

    public CardReport getRoomOccupancyRateCard() {
        return roomOccupancyRateCard;
    }

    public void setRoomOccupancyRateCard(CardReport roomOccupancyRateCard) {
        this.roomOccupancyRateCard = roomOccupancyRateCard;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CardReport bookingRateCard;
    private CardReport numberCheckInCard;
    private CardReport revenueCard;
    private CardReport roomOccupancyRateCard;
    // End of variables declaration//GEN-END:variables
}
