
package iuh.fit.se.group1.ui.component.menu;

import iuh.fit.se.group1.dto.EmployeeDTO;
import iuh.fit.se.group1.ui.component.custom.AvatarLabel;

import javax.swing.*;
import java.awt.*;

public class Footer extends JPanel {

    /**
     * Creates new form Footer
     */
    public Footer() {
        initComponents();

    }

    public void setEmployeeInfo(EmployeeDTO employee) {
        profileButton.setEmployeeInfo(employee);
    }

    public void updateAvatar(byte[] avatarBytes) {
        profileButton.updateAvatar(avatarBytes);
    }

    public void setFullName(String fullName) {
        profileButton.setFullName(fullName);
    }

    public void setRoleName(String roleName) {
        profileButton.setRoleName(roleName);
    }

    public AvatarLabel geLblAvt() {
        return profileButton.getLblAvartar();
    }

    public JButton getBtnSignOut() {
        return profileButton.getBtnSignOut();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profileButton = new ProfileButton();

        setBackground(new Color(255, 255, 255));
        setPreferredSize(new Dimension(267, 137));

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(profileButton, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(profileButton, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ProfileButton profileButton;
    // End of variables declaration//GEN-END:variables
}
