/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.menu;

import iuh.fit.se.group1.ui.component.custom.AvatarLabel;
import iuh.fit.se.group1.ui.component.scroll.ScrollPaneWin11;

import javax.swing.*;
import javax.swing.border.MatteBorder;
import java.awt.*;

/**
 * @author THIS PC
 */
public class SideBar extends JPanel {

    /**
     * Creates new form SideBar
     */
    public SideBar() {
        initComponents();
        footer1.setBorder(new MatteBorder(new Insets(1, 0, 0, 0), Color.BLACK));

    }


    public JButton getBtnSignOut(){
        return footer1.getBtnSignOut();
    }
    public Footer getFooter1() {
        return footer1;
    }
    
    public AvatarLabel getLblAvt(){
       return footer1.geLblAvt();
    }

    public Logo getLogo1() {
        return logo1;
    }

    public Menu getMenu1() {
        return menu1;
    }

    public ScrollPaneWin11 getScrollPaneWin111() {
        return scrollPaneWin111;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo1 = new Logo();
        scrollPaneWin111 = new ScrollPaneWin11();
        menu1 = new Menu();
        footer1 = new Footer();

        setBackground(new Color(255, 255, 255));

        scrollPaneWin111.setViewportView(menu1);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(logo1, GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
            .addComponent(scrollPaneWin111, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(footer1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logo1, GroupLayout.PREFERRED_SIZE, 186, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneWin111, GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(footer1, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Footer footer1;
    private Logo logo1;
    private Menu menu1;
    private ScrollPaneWin11 scrollPaneWin111;
    // End of variables declaration//GEN-END:variables
}
