/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.chart;

import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author hoxuy
 */

public class Card extends JPanel {

    // Khai báo biến góc bo ở cấp class
    private int cornerRadius = 5; // chỉnh 30 hay 20 tuỳ bạn muốn bo cong nhiều ít
    

    public Card() {
        initComponents();
        setOpaque(false); // để panel có thể bo góc nhìn thấy
        lbl5.setIcon(FontIcon.of(FontAwesomeSolid.DOLLAR_SIGN, 30, Color.WHITE));
    }

    @Override
    protected void paintComponent(Graphics g) {
        // Vẽ nền bo góc
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), cornerRadius, cornerRadius);

        g2.dispose();

        // Gọi super để vẽ tiếp các component con (label, textfield,...)
        super.paintComponent(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        lbl1 = new JLabel();
        lbl2 = new JLabel();
        lbl3 = new JLabel();
        lblTotalRevenue = new JLabel();
        criclePanel2 = new iuh.fit.se.group1.ui.component.custom.CriclePanel();
        lbl5 = new JLabel();

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new Color(255, 255, 255));
        setBorder(BorderFactory.createMatteBorder(5, 0, 0, 0, new Color(143, 191, 250)));
        setPreferredSize(new java.awt.Dimension(690, 184));

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl1.setForeground(new Color(140, 140, 140));
        lbl1.setText("TỔNG DOANH THU ");
        lbl1.setPreferredSize(new java.awt.Dimension(690, 184));

        lbl2.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        lbl2.setForeground(new Color(235, 39, 39));
        lbl2.setText("Xem chi tiết");
        lbl2.setPreferredSize(new java.awt.Dimension(168, 28));

        lbl3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl3.setForeground(new Color(91, 189, 64));
        lbl3.setText("Tăng 20% so với tháng trước");
        lbl3.setPreferredSize(new java.awt.Dimension(168, 28));

        lblTotalRevenue.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTotalRevenue.setForeground(new Color(51, 51, 51));
        lblTotalRevenue.setText("235.500.000đ");
        lblTotalRevenue.setPreferredSize(new java.awt.Dimension(168, 28));

        criclePanel2.setMinimumSize(new java.awt.Dimension(40, 40));
        criclePanel2.setPreferredSize(new java.awt.Dimension(60, 60));

        lbl5.setBackground(new Color(143, 191, 250));
        lbl5.setForeground(new Color(143, 191, 250));

        GroupLayout criclePanel2Layout = new GroupLayout(criclePanel2);
        criclePanel2.setLayout(criclePanel2Layout);
        criclePanel2Layout.setHorizontalGroup(
            criclePanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(criclePanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbl5, GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );
        criclePanel2Layout.setVerticalGroup(
            criclePanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(criclePanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbl5, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl3, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalRevenue, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addComponent(lbl1, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(93, 93, 93)
                .addComponent(criclePanel2, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lbl1, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalRevenue, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(criclePanel2, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setLabel (String title , Color color, Icon icon) {
        criclePanel2.setBackground(color);
        lbl5.setIcon(icon);
        lbl1.setText(title);
    }

    public void setValue(String totalRevenue) {
        lblTotalRevenue.setText(totalRevenue);
        lbl3.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private iuh.fit.se.group1.ui.component.custom.CriclePanel criclePanel2;
    private JPanel jPanel1;
    private JLabel lbl1;
    private JLabel lbl2;
    private JLabel lbl3;
    private JLabel lbl5;
    private JLabel lblTotalRevenue;
    // End of variables declaration//GEN-END:variables
}
