/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.chart;

import javax.swing.*;
import java.awt.*;
import java.awt.geom.Path2D;

/**
 *
 * @author THIS PC
 */
public class CardLiquid extends JPanel {

    private int cornerRadius = 20;   // bo tròn góc
    private int shadowSize = 4;      // độ dày bóng

    /**
     * Creates new form CardLiquid
     */
    public CardLiquid() {
        initComponents();
        setOpaque(false);

    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        int width = getWidth();
        int height = getHeight();
        int r = cornerRadius;    // bán kính bo góc
        int shadow = shadowSize; // độ lệch bóng

        // --- (Tuỳ chọn) Vẽ bóng mờ ---
        if (shadow > 0) {
            g2.setColor(new Color(0, 0, 0, 40)); // bóng đen mờ
            Shape shadowShape = createRoundedShape(width - shadow, height - shadow, r, r, r, r);
            g2.translate(shadow, shadow);
            g2.fill(shadowShape);
            g2.translate(-shadow, -shadow);
        }

        // --- Vẽ nền panel ---
        g2.setColor(getBackground());
        Shape shape = createRoundedShape(width, height, r, r, r, r);
        g2.fill(shape);

        g2.dispose();
    }

    /**
     * Tạo hình có thể bo riêng từng góc
     */
    private Shape createRoundedShape(int width, int height, int tl, int tr, int br, int bl) {
        Path2D path = new Path2D.Float();
        path.moveTo(0, tl);
        path.quadTo(0, 0, tl, 0);                   // top-left
        path.lineTo(width - tr, 0);
        path.quadTo(width, 0, width, tr);           // top-right
        path.lineTo(width, height - br);
        path.quadTo(width, height, width - br, height); // bottom-right
        path.lineTo(bl, height);
        path.quadTo(0, height, 0, height - bl);     // bottom-left
        path.closePath();
        return path;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jLabel1 = new javax.swing.JLabel();
        liquidProgress1 = new LiquidProgress();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new JPanel();

        setBackground(new Color(255, 255, 255));

        jPanel1.setBackground(new Color(255, 255, 255));

        jLabel1.setBackground(new Color(97, 94, 131));
        jLabel1.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new Color(97, 94, 131));
        jLabel1.setText("Tỉ lệ lắp đầy phòng đơn");

        jLabel2.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new Color(153, 255, 102));
        jLabel2.setText("2000/4000 lượt");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(liquidProgress1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(liquidProgress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private LiquidProgress liquidProgress1;
    // End of variables declaration//GEN-END:variables

    // ==================== Public API Methods ====================

    /**
     * Set tiêu đề cho card
     */
    public void setTitle(String title) {
        jLabel1.setText(title);
    }

    /**
     * Set mô tả cho card
     */
    public void setDescription(String description) {
        jLabel2.setText(description);
    }

    /**
     * Set giá trị % cho liquid progress
     * @param percentage Phần trăm (có thể vượt 100, ví dụ: 150%, 200%...)
     */
    public void setValues(int percentage) {
        // LiquidProgress luôn dùng maximum = 100 để render đúng
        liquidProgress1.setMaximum(100);

        // Nếu % > 100, fill đầy thanh (100%)
        // Nếu % <= 100, fill theo % thực tế
        int displayValue = Math.min(percentage, 100);
        liquidProgress1.setValue(displayValue);

        // Hiển thị text % thực tế (có thể >100)
        liquidProgress1.setString(percentage + "%");
    }

    /**
     * Get tiêu đề hiện tại
     */
    public String getTitle() {
        return jLabel1.getText();
    }

    /**
     * Get mô tả hiện tại
     */
    public String getDescription() {
        return jLabel2.getText();
    }
}
