/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.chart;

import iuh.fit.se.group1.ui.component.booking2.CalendarUI;
import iuh.fit.se.group1.ui.component.custom.Button;
import iuh.fit.se.group1.ui.component.custom.TextField;

import javax.swing.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author THIS PC
 */
public class HeaderChart extends JPanel {
    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }



    public TextField getTxtFromDate() {
        return txtFromDate;
    }

    public void setTxtFromDate(TextField txtFromDate) {
        this.txtFromDate = txtFromDate;
    }

    public TextField getTxtToDate() {
        return txtToDate;
    }

    public void setTxtToDate(TextField txtToDate) {
        this.txtToDate = txtToDate;
    }

    /**
     * Creates new form HeaderChart
     */
    public HeaderChart() {
        initComponents();
        txtFromDate.setEditable(false);
        txtToDate.setEditable(false);
        txtFromDate.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        txtToDate.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));

        txtFromDate.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalendarUI.showCalendar(txtFromDate, null, null, false);
            }
        });

        txtToDate.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalendarUI.showCalendar(txtToDate, null, null, false);
            }
        });
    }

    public Button getBtnView() {
        return btnView;
    }

    public void setBtnView(Button btnView) {
        this.btnView = btnView;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        btnView = new Button();
        txtFromDate = new TextField();
        txtToDate = new TextField();
        jLabel3 = new JLabel();

        setBackground(new java.awt.Color(108, 165, 200));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(246, 246, 246));
        jLabel1.setText("Quản lí thống kê");

        btnView.setBackground(new java.awt.Color(255, 108, 3));
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("Xem");
        btnView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtFromDate.setEditable(false);
        txtFromDate.setBackground(new java.awt.Color(108, 165, 200));
        txtFromDate.setForeground(new java.awt.Color(255, 255, 255));
        txtFromDate.setText("textField1");
        txtFromDate.setBorderColor(java.awt.Color.white);
        txtFromDate.setBorderRadius(5);
        txtFromDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtToDate.setBackground(new java.awt.Color(108, 165, 200));
        txtToDate.setForeground(new java.awt.Color(255, 255, 255));
        txtToDate.setText("textField1");
        txtToDate.setBorderColor(java.awt.Color.white);
        txtToDate.setBorderRadius(5);
        txtToDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel3.setText("đến");

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 328, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(txtFromDate, GroupLayout.PREFERRED_SIZE, 128, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtToDate, GroupLayout.PREFERRED_SIZE, 128, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnView, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addComponent(btnView, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(txtFromDate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(txtToDate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Button btnView;
    private JLabel jLabel1;
    private JLabel jLabel3;
    private TextField txtFromDate;
    private TextField txtToDate;
    // End of variables declaration//GEN-END:variables
}
