/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.chart;

import iuh.fit.se.group1.enums.TimeType;
import iuh.fit.se.group1.ui.component.custom.Button;

/**
 *
 * @author THIS PC
 */
public class RangeDateButton extends javax.swing.JPanel {

    /**
     * Creates new form RangeDateButton
     */
    public RangeDateButton() {
        initComponents();
        setActiveButton(TimeType.DAYS_7);
    }

    public void setActiveButton(TimeType timeType) {
        // timeType:2 - 7 days, 3 - 30 days, 4 - 90 days
        Button[] btns = { btn7Days, btn30Days, btn90Days};
        for (int i = 0; i < btns.length; i++) {
            if (i == timeType.getValue() - 2) {
                btns[i].setBackground(new java.awt.Color(0, 123, 255));
                btns[i].setForeground(new java.awt.Color(255, 255, 255));
            } else {
                btns[i].setBackground(new java.awt.Color(214,217,223));
                btns[i].setForeground(new java.awt.Color(0, 0, 0));
            }
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn7Days = new Button();
        btn30Days = new Button();
        btn90Days = new Button();

        setBackground(new java.awt.Color(242, 241, 241));

        btn7Days.setBackground(new java.awt.Color(218, 218, 218));
        btn7Days.setForeground(new java.awt.Color(172, 172, 172));
        btn7Days.setText("7 Ngày");
        btn7Days.setBorderRadius(5);

        btn30Days.setBackground(new java.awt.Color(218, 218, 218));
        btn30Days.setForeground(new java.awt.Color(172, 172, 172));
        btn30Days.setText("30 Ngày");
        btn30Days.setBorderRadius(5);

        btn90Days.setBackground(new java.awt.Color(218, 218, 218));
        btn90Days.setForeground(new java.awt.Color(172, 172, 172));
        btn90Days.setText("90 Ngày");
        btn90Days.setBorderRadius(5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btn7Days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btn30Days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btn90Days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7Days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn30Days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn90Days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    public Button getBtn30Days() {
        return btn30Days;
    }

    public void setBtn30Days(Button btn30Days) {
        this.btn30Days = btn30Days;
    }

    public Button getBtn7Days() {
        return btn7Days;
    }

    public void setBtn7Days(Button btn7Days) {
        this.btn7Days = btn7Days;
    }

    public Button getBtn90Days() {
        return btn90Days;
    }

    public void setBtn90Days(Button btn90Days) {
        this.btn90Days = btn90Days;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Button btn30Days;
    private Button btn7Days;
    private Button btn90Days;
    // End of variables declaration//GEN-END:variables
}
