/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.layout;

import java.awt.*;

/**
 *
 * @author Windows
 */
public class InstructionsForUser extends javax.swing.JPanel {

    /**
     * Creates new form InstructionsForUser
     */
    public InstructionsForUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailedInstructions1 = new iuh.fit.se.group1.ui.component.instructions.DetailedInstructions();
        criclePanel1 = new iuh.fit.se.group1.ui.component.custom.CriclePanel();
        jLabel1 = new javax.swing.JLabel();
        detailedInstructions2 = new iuh.fit.se.group1.ui.component.instructions.DetailedInstructions();
        criclePanel4 = new iuh.fit.se.group1.ui.component.custom.CriclePanel();
        jLabel4 = new javax.swing.JLabel();
        detailedInstructions3 = new iuh.fit.se.group1.ui.component.instructions.DetailedInstructions();
        criclePanel2 = new iuh.fit.se.group1.ui.component.custom.CriclePanel();
        jLabel2 = new javax.swing.JLabel();
        detailedInstructions4 = new iuh.fit.se.group1.ui.component.instructions.DetailedInstructions();
        criclePanel5 = new iuh.fit.se.group1.ui.component.custom.CriclePanel();
        jLabel5 = new javax.swing.JLabel();
        detailedInstructions5 = new iuh.fit.se.group1.ui.component.instructions.DetailedInstructions();
        criclePanel3 = new iuh.fit.se.group1.ui.component.custom.CriclePanel();
        jLabel3 = new javax.swing.JLabel();
        detailedInstructions6 = new iuh.fit.se.group1.ui.component.instructions.DetailedInstructions();
        criclePanel6 = new iuh.fit.se.group1.ui.component.custom.CriclePanel();
        jLabel6 = new javax.swing.JLabel();
        headerShift1 = new iuh.fit.se.group1.ui.component.HeaderShift();

        detailedInstructions1.setBackground(new java.awt.Color(153, 204, 255));

        criclePanel1.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout criclePanel1Layout = new javax.swing.GroupLayout(criclePanel1);
        criclePanel1.setLayout(criclePanel1Layout);
        criclePanel1Layout.setHorizontalGroup(
            criclePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );
        criclePanel1Layout.setVerticalGroup(
            criclePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("   ");

        javax.swing.GroupLayout detailedInstructions1Layout = new javax.swing.GroupLayout(detailedInstructions1);
        detailedInstructions1.setLayout(detailedInstructions1Layout);
        detailedInstructions1Layout.setHorizontalGroup(
            detailedInstructions1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailedInstructions1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(criclePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        detailedInstructions1Layout.setVerticalGroup(
            detailedInstructions1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailedInstructions1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(criclePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(detailedInstructions1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        criclePanel4.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout criclePanel4Layout = new javax.swing.GroupLayout(criclePanel4);
        criclePanel4.setLayout(criclePanel4Layout);
        criclePanel4Layout.setHorizontalGroup(
            criclePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );
        criclePanel4Layout.setVerticalGroup(
            criclePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        jLabel4.setText("     ");

        javax.swing.GroupLayout detailedInstructions2Layout = new javax.swing.GroupLayout(detailedInstructions2);
        detailedInstructions2.setLayout(detailedInstructions2Layout);
        detailedInstructions2Layout.setHorizontalGroup(
            detailedInstructions2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailedInstructions2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(criclePanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(25, 25, 25))
        );
        detailedInstructions2Layout.setVerticalGroup(
            detailedInstructions2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailedInstructions2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(criclePanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(detailedInstructions2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        criclePanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout criclePanel2Layout = new javax.swing.GroupLayout(criclePanel2);
        criclePanel2.setLayout(criclePanel2Layout);
        criclePanel2Layout.setHorizontalGroup(
            criclePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );
        criclePanel2Layout.setVerticalGroup(
            criclePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        jLabel2.setText("    ");

        javax.swing.GroupLayout detailedInstructions3Layout = new javax.swing.GroupLayout(detailedInstructions3);
        detailedInstructions3.setLayout(detailedInstructions3Layout);
        detailedInstructions3Layout.setHorizontalGroup(
            detailedInstructions3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailedInstructions3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(criclePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        detailedInstructions3Layout.setVerticalGroup(
            detailedInstructions3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailedInstructions3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(criclePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(detailedInstructions3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        criclePanel5.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout criclePanel5Layout = new javax.swing.GroupLayout(criclePanel5);
        criclePanel5.setLayout(criclePanel5Layout);
        criclePanel5Layout.setHorizontalGroup(
            criclePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );
        criclePanel5Layout.setVerticalGroup(
            criclePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        jLabel5.setText("     ");

        javax.swing.GroupLayout detailedInstructions4Layout = new javax.swing.GroupLayout(detailedInstructions4);
        detailedInstructions4.setLayout(detailedInstructions4Layout);
        detailedInstructions4Layout.setHorizontalGroup(
            detailedInstructions4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailedInstructions4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(criclePanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(26, 26, 26))
        );
        detailedInstructions4Layout.setVerticalGroup(
            detailedInstructions4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailedInstructions4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(criclePanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(detailedInstructions4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        criclePanel3.setBackground(new java.awt.Color(153, 153, 153));
        criclePanel3.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout criclePanel3Layout = new javax.swing.GroupLayout(criclePanel3);
        criclePanel3.setLayout(criclePanel3Layout);
        criclePanel3Layout.setHorizontalGroup(
            criclePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );
        criclePanel3Layout.setVerticalGroup(
            criclePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        jLabel3.setText("    ");

        javax.swing.GroupLayout detailedInstructions5Layout = new javax.swing.GroupLayout(detailedInstructions5);
        detailedInstructions5.setLayout(detailedInstructions5Layout);
        detailedInstructions5Layout.setHorizontalGroup(
            detailedInstructions5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailedInstructions5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(criclePanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        detailedInstructions5Layout.setVerticalGroup(
            detailedInstructions5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailedInstructions5Layout.createSequentialGroup()
                .addGroup(detailedInstructions5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailedInstructions5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(criclePanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detailedInstructions5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        criclePanel6.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout criclePanel6Layout = new javax.swing.GroupLayout(criclePanel6);
        criclePanel6.setLayout(criclePanel6Layout);
        criclePanel6Layout.setHorizontalGroup(
            criclePanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );
        criclePanel6Layout.setVerticalGroup(
            criclePanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        jLabel6.setText("    ");

        javax.swing.GroupLayout detailedInstructions6Layout = new javax.swing.GroupLayout(detailedInstructions6);
        detailedInstructions6.setLayout(detailedInstructions6Layout);
        detailedInstructions6Layout.setHorizontalGroup(
            detailedInstructions6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailedInstructions6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(criclePanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(19, 19, 19))
        );
        detailedInstructions6Layout.setVerticalGroup(
            detailedInstructions6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailedInstructions6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(criclePanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailedInstructions6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerShift1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(detailedInstructions5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailedInstructions3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailedInstructions1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(detailedInstructions2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailedInstructions4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailedInstructions6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerShift1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(detailedInstructions2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailedInstructions1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(detailedInstructions3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailedInstructions4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(detailedInstructions5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailedInstructions6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 385, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20); 
        g2.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private iuh.fit.se.group1.ui.component.custom.CriclePanel criclePanel1;
    private iuh.fit.se.group1.ui.component.custom.CriclePanel criclePanel2;
    private iuh.fit.se.group1.ui.component.custom.CriclePanel criclePanel3;
    private iuh.fit.se.group1.ui.component.custom.CriclePanel criclePanel4;
    private iuh.fit.se.group1.ui.component.custom.CriclePanel criclePanel5;
    private iuh.fit.se.group1.ui.component.custom.CriclePanel criclePanel6;
    private iuh.fit.se.group1.ui.component.instructions.DetailedInstructions detailedInstructions1;
    private iuh.fit.se.group1.ui.component.instructions.DetailedInstructions detailedInstructions2;
    private iuh.fit.se.group1.ui.component.instructions.DetailedInstructions detailedInstructions3;
    private iuh.fit.se.group1.ui.component.instructions.DetailedInstructions detailedInstructions4;
    private iuh.fit.se.group1.ui.component.instructions.DetailedInstructions detailedInstructions5;
    private iuh.fit.se.group1.ui.component.instructions.DetailedInstructions detailedInstructions6;
    private iuh.fit.se.group1.ui.component.HeaderShift headerShift1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
