/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java
 */
package iuh.fit.se.group1.ui.layout;

import iuh.fit.se.group1.dto.SurchargeDTO;
import iuh.fit.se.group1.network.ClientEventBus;
import iuh.fit.se.group1.network.Response;
import iuh.fit.se.group1.network.client.SocketFacade;
import iuh.fit.se.group1.network.client.service.ImportExportExcelServiceClient;
import iuh.fit.se.group1.network.client.service.SurchargeServiceClient;
import iuh.fit.se.group1.ui.component.custom.message.Message;
import iuh.fit.se.group1.ui.component.modal.SurchageModal;
import iuh.fit.se.group1.ui.component.table.TableActionEvent;
import iuh.fit.se.group1.util.Constants;
import iuh.fit.se.group1.util.ExportUtil;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import raven.glasspanepopup.GlassPanePopup;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileOutputStream;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * @author Windows
 */
public class SurchargeManagement extends JPanel {

    /**
     * Creates new form SurchageManagement
     */
    private static final Logger log = LoggerFactory.getLogger(SurchargeManagement.class);
    private final SurchargeServiceClient surchargeService;

    private static final int GET_ALL = 0;
    private static final int GET_BY_KEYWORD = 1;
    private boolean subscribed = false;

    public SurchargeManagement() {
        initComponents();
        custom();
        surchargeService = SocketFacade.getInstance().getSurcharge();
        loadTable(fetchData(GET_ALL, null));

        if (!subscribed) {
            ClientEventBus.surchargeEventBus.subscribe(response -> {
                SwingUtilities.invokeLater(this::reloadSurchargeTable);
            });
            subscribed = true;
        }
    }

    private void reloadSurchargeTable() {
        loadTable(fetchData(GET_ALL, null));
    }

    private List<SurchargeDTO> fetchData(int type, String filter) {

        try {

            Response response = null;

            if (type == GET_ALL) {
                response = surchargeService.getAllSurcharges();
            } else if (type == GET_BY_KEYWORD) {
                response = surchargeService.getSurchargeByKeyword(filter);
            }

            if (response == null || response.getCode() != 200) {
                JOptionPane.showMessageDialog(null, "Lỗi khi tải dữ liệu phụ phí: "
                        + (response != null ? response.getMessage() : "Không có phản hồi từ server"));
                return List.of();
            }

            return (List<SurchargeDTO>) response.getData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            throw new RuntimeException(e);
        }

    }

    private void loadTable(List<SurchargeDTO> allSurcharges) {
        DefaultTableModel model = (DefaultTableModel) tblSurchage.getTbl().getModel();
        model.setRowCount(0);
        for (SurchargeDTO surcharge : allSurcharges) {
            model.addRow(new Object[] { surcharge.getSurchargeId(), surcharge.getName(),
                    Constants.VND_FORMAT.format(surcharge.getPrice()) });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerCustom1 = new iuh.fit.se.group1.ui.component.HeaderCustom();
        tblSurchage = new iuh.fit.se.group1.ui.component.table.Table();
        jLabel1 = new JLabel();
        btnAddSurchage = new iuh.fit.se.group1.ui.component.custom.Button();
        btnExport = new iuh.fit.se.group1.ui.component.custom.Button();
        btnImport = new iuh.fit.se.group1.ui.component.custom.Button();

        setBackground(new Color(241, 241, 241));

        tblSurchage.setBorder(BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setBackground(new Color(241, 242, 241));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new Color(102, 102, 102));
        jLabel1.setText("Quản lý phụ phí");

        btnAddSurchage.setText("Thêm phụ phí");
        btnAddSurchage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddSurchage.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnAddSurchageActionPerformed(evt);
            }
        });

        btnExport.setText("Xuất Excel");
        btnExport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnImport.setText("Nhập excel");
        btnImport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnImport.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tblSurchage, GroupLayout.PREFERRED_SIZE, 1200,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addComponent(headerCustom1, GroupLayout.PREFERRED_SIZE,
                                                GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 250,
                                                        GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
                                                        GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnAddSurchage, GroupLayout.PREFERRED_SIZE, 145,
                                                        GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnExport, GroupLayout.PREFERRED_SIZE, 137,
                                                        GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnImport, GroupLayout.PREFERRED_SIZE, 133,
                                                        GroupLayout.PREFERRED_SIZE)
                                                .addGap(86, 86, 86)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(headerCustom1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                        GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(btnExport, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(btnAddSurchage, GroupLayout.DEFAULT_SIZE,
                                                GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnImport, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(tblSurchage, GroupLayout.PREFERRED_SIZE, 642,
                                        GroupLayout.PREFERRED_SIZE)));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSurchageActionPerformed(ActionEvent evt) {// GEN-FIRST:event_btnAddSurchageActionPerformed
        SurchageModal modal = new SurchageModal();
        modal.closeModel(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                GlassPanePopup.closePopupLast();
            }

        });
        modal.saveData(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                try {
                    saveData(modal);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }

            private void saveData(SurchageModal modal) throws Exception {
                Valid result = getValid(modal);
                if (result.valid()) {

                    Response response = surchargeService.createSurcharge(SurchargeDTO.builder()
                            .name(result.name())
                            .price(result.price())
                            .build());

                    if (response.getCode() != 200 || response == null) {
                        JOptionPane.showMessageDialog(null,
                                "Lỗi khi tạo phụ phí: "
                                        + (response != null ? response.getMessage() : "Không có phản hồi từ server"),
                                "Lỗi", JOptionPane.ERROR_MESSAGE);
                        return;
                    }

                    SurchargeDTO surchargeSave = (SurchargeDTO) response.getData();
                    if (surchargeSave == null) {
                        Message.showMessage("Lỗi", "Phụ phí với tên '" + result.name() + "' đã tồn tại!");
                        return;
                    }
                    DefaultTableModel model = (DefaultTableModel) tblSurchage.getTbl().getModel();
                    model.addRow(new Object[] { surchargeSave.getSurchargeId(), surchargeSave.getName(),
                            Constants.VND_FORMAT.format(surchargeSave.getPrice()) });
                    GlassPanePopup.closePopupLast();
                }
            }
        });
        GlassPanePopup.showPopup(modal);
    }// GEN-LAST:event_btnAddSurchageActionPerformed

    private void btnImportActionPerformed(ActionEvent evt) {// GEN-FIRST:event_btnImportActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnImportActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private iuh.fit.se.group1.ui.component.custom.Button btnAddSurchage;
    private iuh.fit.se.group1.ui.component.custom.Button btnExport;
    private iuh.fit.se.group1.ui.component.custom.Button btnImport;
    private iuh.fit.se.group1.ui.component.HeaderCustom headerCustom1;
    private JLabel jLabel1;
    private iuh.fit.se.group1.ui.component.table.Table tblSurchage;
    // End of variables declaration//GEN-END:variables

    private void custom() {

        headerCustom1.getLblTitle().setText(
                "<html><span style='color:white;'>Quản lý phụ phí</span>");
        headerCustom1.getLblTitle().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));

        btnAddSurchage.setBackground(new Color(108, 165, 200));
        btnAddSurchage.setForeground(Color.WHITE);
        btnAddSurchage.setBorderRadius(10);

        btnExport.setBackground(new Color(13, 200, 7));
        btnExport.setForeground(Color.WHITE);
        btnExport.setBorderRadius(10);
        btnExport.addActionListener(e -> {
            try {
                byte[] data = ExportUtil.exportTableToExcel(
                        tblSurchage.getTbl(),
                        "Danh sách phụ phí",
                        true);

                JFileChooser fileChooser = new JFileChooser();
                fileChooser.setDialogTitle("Lưu file Excel");

                // ✔ tên file mặc định
                String defaultFileName = "DanhSachPhuPhi_" +
                        LocalDate.now().format(DateTimeFormatter.ofPattern("ddMMyyyy")) + ".xlsx";

                fileChooser.setSelectedFile(new File(defaultFileName));

                int result = fileChooser.showSaveDialog(this);

                if (result == JFileChooser.APPROVE_OPTION) {
                    File file = fileChooser.getSelectedFile();

                    if (!file.getName().toLowerCase().endsWith(".xlsx")) {
                        file = new File(file.getAbsolutePath() + ".xlsx");
                    }

                    try (FileOutputStream fos = new FileOutputStream(file)) {
                        fos.write(data);
                    }

                    Message.showMessage("Thành công", "Đã lưu file: " + file.getAbsolutePath());
                }

            } catch (Exception ex) {
                Message.showMessage("Lỗi", ex.getMessage());
            }
        });

        btnImport.setBackground(new Color(255, 108, 3));
        btnImport.setForeground(Color.WHITE);
        btnImport.setBorderRadius(10);
        btnImport.addActionListener(ev -> {
            JFileChooser fileChooser = new JFileChooser();
            int result = fileChooser.showOpenDialog(this);
            try {
                if (result == JFileChooser.APPROVE_OPTION) {
                    File file = fileChooser.getSelectedFile();
                    ImportExportExcelServiceClient importService = SocketFacade.getInstance().getImportExportExcel();

                    Response response = importService.importSurchargesFromExcel(file);

                    List<SurchargeDTO> imported = (List<SurchargeDTO>) response.getData();
                    if (imported != null && !imported.isEmpty()) {
                        loadTable(fetchData(GET_ALL, null));
                        Message.showMessage("Thành công", "Đã import " + imported.size() + " phụ phí!");
                    } else {
                        Message.showMessage("Lỗi", "Không có dữ liệu nào được import!");
                    }
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage(), "Lỗi nhập Excel",
                        JOptionPane.ERROR_MESSAGE);

            }
        });
        btnAddSurchage.setIcon(FontIcon.of(FontAwesomeSolid.PLUS, 17, Color.WHITE), SwingConstants.RIGHT);
        btnImport.setIcon(FontIcon.of(FontAwesomeSolid.FILE_IMPORT, 17, Color.WHITE), SwingConstants.RIGHT);
        btnExport.setIcon(FontIcon.of(FontAwesomeSolid.FILE_EXPORT, 17, Color.WHITE), SwingConstants.RIGHT);

        String cols[] = { "Mã phụ phí", "Tên phụ phí", "Giá phụ phí", "Chức năng" };
        DefaultTableModel model = new DefaultTableModel(cols, 0);

        // Khởi tạo TableRowSorter cho chức năng tìm kiếm
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblSurchage.getTbl().setRowSorter(sorter);
        tblSurchage.getTbl().setAutoCreateRowSorter(false);

        // Tắt sorting cho tất cả các cột
        for (int i = 0; i < cols.length; i++) {
            sorter.setSortable(i, false);
        }

        tblSurchage.getTbl().setModel(model);

        TableActionEvent event = new TableActionEvent() {
            @Override
            public void onEdit(int row) {
                DefaultTableModel model = (DefaultTableModel) tblSurchage.getTbl().getModel();
                String name = (String) model.getValueAt(row, 1);
                String price = String.valueOf(model.getValueAt(row, 2));

                SurchageModal modal = new SurchageModal();
                modal.getLblTitle().setText("Cập nhật phụ phí");
                modal.getBtnSave().setText("Cập nhật");

                modal.getTxtName().setText(name);
                modal.getTxtPrice().setText(price);

                modal.closeModel(ae -> GlassPanePopup.closePopupLast());
                modal.saveData(ae -> {
                    String title = "Xác nhận cập nhật phụ phí";
                    String message = "Bạn có chắc chắn muốn cập nhật phụ phí này không?";
                    Message.showConfirm(title, message, () -> {
                        try {
                            var result = getValid(modal);
                            if (!result.valid) {
                                return;
                            }
                            Object idValue = model.getValueAt(row, 0);

                            Response response = surchargeService.updateSurcharge(
                                    SurchargeDTO.builder()
                                            .surchargeId((Long) idValue)
                                            .price(result.price())
                                            .name(result.name())
                                            .build());

                            if (response == null || response.getCode() != 200) {
                                JOptionPane.showMessageDialog(null, "Lỗi khi cập nhật phụ phí: "
                                        + (response != null ? response.getMessage() : "Không có phản hồi từ server"),
                                        "Lỗi", JOptionPane.ERROR_MESSAGE);
                                return;
                            }

                            SurchargeDTO entitySave = (SurchargeDTO) response.getData();

                            model.setValueAt(entitySave.getName(), row, 1);
                            model.setValueAt(Constants.VND_FORMAT.format(entitySave.getPrice()), row, 2);

                            GlassPanePopup.closePopupLast();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                            throw new RuntimeException(ex);
                        }
                    });
                });

                GlassPanePopup.showPopup(modal);
            }

            @Override
            public void onDelete(int row) {
                String title = "Xác nhận xóa phụ phí";
                String message = "Bạn có chắc chắn muốn xóa phụ phí này không?";
                Message.showConfirm(title, message, () -> {
                    JTable table = tblSurchage.getTbl();

                    if (table.isEditing()) {
                        table.getCellEditor().stopCellEditing();
                    }

                    DefaultTableModel model = (DefaultTableModel) table.getModel();
                    int rowDelete = table.getSelectedRow();

                    if (rowDelete >= 0) {
                        Long id = (Long) model.getValueAt(rowDelete, 0);

                        model.removeRow(rowDelete);

                        try {
                            Response response = surchargeService.deleteSurcharge(id);
                            if (response == null || response.getCode() != 200) {
                                JOptionPane.showMessageDialog(null, "Lỗi khi xóa phụ phí: "
                                        + (response != null ? response.getMessage() : "Không có phản hồi từ server"),
                                        "Lỗi", JOptionPane.ERROR_MESSAGE);
                            }
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e.getMessage());
                            throw new RuntimeException(e);
                        }
                    }
                });

            }

        };
        tblSurchage.setTableActionColumn(tblSurchage.getTbl(), 3, event, false);
        tblSurchage.getTbl().getColumnModel().getColumn(0).setPreferredWidth(200);
        tblSurchage.getTbl().getColumnModel().getColumn(1).setPreferredWidth(300);
        tblSurchage.getTbl().getColumnModel().getColumn(2).setPreferredWidth(200);
        tblSurchage.getTbl().getColumnModel().getColumn(3).setPreferredWidth(80);

        tblSurchage.getTbl().addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseMoved(java.awt.event.MouseEvent e) {
                int col = tblSurchage.getTbl().columnAtPoint(e.getPoint());
                if (col == 3) {
                    tblSurchage.getTbl().setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                } else {
                    tblSurchage.getTbl().setCursor(Cursor.getDefaultCursor());
                }
            }
        });

        headerCustom1.handleSearch(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filterTable();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filterTable();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filterTable();
            }

            private void filterTable() {
                String keyword = headerCustom1.getSearchText().trim();
                TableRowSorter<DefaultTableModel> sorter = (TableRowSorter<DefaultTableModel>) tblSurchage.getTbl()
                        .getRowSorter();
                if (keyword.isEmpty()) {
                    sorter.setRowFilter(null);
                } else {
                    sorter.setRowFilter(new RowFilter<DefaultTableModel, Integer>() {
                        @Override
                        public boolean include(Entry<? extends DefaultTableModel, ? extends Integer> entry) {
                            // Tìm kiếm theo mã phụ phí (cột 0) hoặc tên phụ phí (cột 1)
                            Object idValue = entry.getValue(0);
                            Object nameValue = entry.getValue(1);

                            if (idValue != null && idValue.toString().contains(keyword)) {
                                return true;
                            }
                            if (nameValue != null
                                    && nameValue.toString().toLowerCase().contains(keyword.toLowerCase())) {
                                return true;
                            }
                            return false;
                        }
                    });
                }
            }

        });

        addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent e) {
                tblSurchage.getTbl().clearSelection();
            }
        });
    }

    private record Valid(String name, boolean valid, BigDecimal price) {

    }

    private static Valid getValid(SurchageModal modal) {
        String name = modal.getTxtName().getText().trim();
        String price = modal.getTxtPrice().getText().trim();

        modal.getLblErrolSurchage().setText("");
        modal.getLblErrolPrice().setText("");

        Color red = Color.RED;
        modal.getLblErrolSurchage().setForeground(red);
        modal.getLblErrolPrice().setForeground(red);

        boolean valid = true;

        if (name.isEmpty()) {
            modal.getLblErrolSurchage().setText("Tên không được để trống!");
            valid = false;
        } else if (name.length() < 2) {
            modal.getLblErrolSurchage().setText("Tên quá ngắn (tối thiểu 2 ký tự)!");
            valid = false;
        }

        BigDecimal priceI = BigDecimal.ZERO;
        if (price.isEmpty()) {
            modal.getLblErrolPrice().setText("Giá không được để trống!");
            valid = false;
        } else {
            try {
                priceI = new BigDecimal(
                        price.replaceAll("[^\\d.-]", "").trim());
                if (priceI.compareTo(BigDecimal.ZERO) <= 0) {
                    modal.getLblErrolPrice().setText("Giá phải lớn hơn 0!");
                    valid = false;
                }
            } catch (Exception e) {
                modal.getLblErrolPrice().setText("Giá phải là số hợp lệ!");
                valid = false;
                log.error("Lỗi chuyển đổi giá dịch vụ: ", e);
            }
        }
        return new Valid(name, valid, priceI);
    }

}