/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.shift;

import iuh.fit.se.group1.ui.component.custom.TextField;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;

import java.awt.*;

/**
 *
 * @author THIS PC
 */
public class InfoShift extends javax.swing.JPanel {

    /**
     * Creates new form InfoShift
     */
    public InfoShift() {
        initComponents();
        setOpaque(false);
        lblTitle.setIcon(FontIcon.of(FontAwesomeSolid.CLOCK,20,Color.BLACK));
    }
    public void setEmployeeName(String name) {
        txtEmployee.setText(name);
    }

    public void setEmployeeId(String id) {
        txtEmployee.setText(txtEmployee.getText() + " (Mã nhân viên: " + id + ")");
    }

    public void setShiftInfo(String name, String time, String date) {
        txtShift.setText(name + " | " + time + " | " + date);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblEmployee = new javax.swing.JLabel();
        txtEmployee = new TextField();
        lblShift = new javax.swing.JLabel();
        txtShift = new TextField();
        pnlNotify = new javax.swing.JPanel();
        lblMiss = new javax.swing.JLabel();
        lblExcess = new javax.swing.JLabel();
        pnlPrice = new javax.swing.JPanel();
        lblCalculatePrice = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        lblNote = new javax.swing.JLabel();

        setBackground(new Color(255, 255, 255));

        lblTitle.setFont(new Font("Segoe UI", 1, 16)); // NOI18N
        lblTitle.setText("Thông tin ca làm");

        lblEmployee.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        lblEmployee.setText("Ca làm việc");

        txtEmployee.setForeground(new Color(153, 153, 153));
        txtEmployee.setBorderRadius(5);
        txtEmployee.setEnabled(false);

        lblShift.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        lblShift.setText("Nhân viên");

        txtShift.setBorderRadius(5);
        txtShift.setEnabled(false);
        txtShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShiftActionPerformed(evt);
            }
        });

        pnlNotify.setBackground(new Color(255, 255, 255));

        lblMiss.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        lblMiss.setForeground(new Color(255, 51, 0));
        lblMiss.setText("MÀU ĐỎ LÀ SỐ TIỀN THIẾU");

        lblExcess.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        lblExcess.setForeground(new Color(0, 153, 0));
        lblExcess.setText("MÀU XANH LÀ SỐ TIỀN THỪA");

        pnlPrice.setBackground(new Color(255, 255, 255));

        javax.swing.GroupLayout pnlPriceLayout = new javax.swing.GroupLayout(pnlPrice);
        pnlPrice.setLayout(pnlPriceLayout);
        pnlPriceLayout.setHorizontalGroup(
            pnlPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );
        pnlPriceLayout.setVerticalGroup(
            pnlPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        lblCalculatePrice.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        lblCalculatePrice.setText("CÁCH TÍNH TIỀN :");

        lblTotalPrice.setBackground(new Color(255, 255, 255));
        lblTotalPrice.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalPrice.setText("THỰC TẾ = ĐÓNG CA + HỆ THỐNG");

        lblNote.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        lblNote.setForeground(new Color(102, 102, 102));
        lblNote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNote.setText("CHÚ THÍCH:");

        javax.swing.GroupLayout pnlNotifyLayout = new javax.swing.GroupLayout(pnlNotify);
        pnlNotify.setLayout(pnlNotifyLayout);
        pnlNotifyLayout.setHorizontalGroup(
            pnlNotifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNotifyLayout.createSequentialGroup()
                .addComponent(lblNote, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNotifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCalculatePrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlNotifyLayout.createSequentialGroup()
                        .addGroup(pnlNotifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMiss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblExcess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlNotifyLayout.createSequentialGroup()
                                .addComponent(lblTotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlNotifyLayout.setVerticalGroup(
            pnlNotifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNotifyLayout.createSequentialGroup()
                .addGroup(pnlNotifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMiss, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlNotifyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0)
                .addComponent(lblExcess, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblCalculatePrice)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlNotifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblShift, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtShift, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlNotify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployee)
                    .addComponent(lblShift))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtShift, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlNotify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShiftActionPerformed


    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20); // 20 = độ bo góc
        g2.dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCalculatePrice;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JLabel lblExcess;
    private javax.swing.JLabel lblMiss;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblShift;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JPanel pnlNotify;
    private javax.swing.JPanel pnlPrice;
    private TextField txtEmployee;
    private TextField txtShift;
    // End of variables declaration//GEN-END:variables
}
