/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.shift;

import iuh.fit.se.group1.ui.component.custom.TextField;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Windows
 */
public class Money extends javax.swing.JPanel {

    public JLabel getLblMoney() {
        return lblMoney;
    }

    public void setLblMoney(JLabel lblMoney) {
        this.lblMoney = lblMoney;
    }

    public JLabel getLblQuantity() {
        return lblQuantity;
    }

    public void setLblQuantity(JLabel lblQuantity) {
        this.lblQuantity = lblQuantity;
    }

    public TextField getTxtMoney() {
        return txtMoney;
    }

    public void setTxtMoney(TextField txtMoney) {
        this.txtMoney = txtMoney;
    }

    public TextField getTxtQuantity() {
        return txtMoney;
    }

    public void setTxtQuantity(TextField txtQuantity) {
        this.txtMoney = txtQuantity;
    }


    /**
     * Creates new form Money
     */
    public Money() {
        initComponents();
        setOpaque(false);
        txtMoney.setText("");
        txtMoney.setPreferredSize(new java.awt.Dimension(80, 25));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMoney = new JLabel();
        lblQuantity = new JLabel();
        txtMoney = new TextField();

        setBackground(new Color(255, 255, 255));
        setBorder(new javax.swing.border.MatteBorder(null));
        setForeground(new Color(153, 153, 153));

        lblMoney.setText("500.000đ");

        lblQuantity.setText("Số lượng");

        txtMoney.setForeground(new Color(153, 153, 153));
        txtMoney.setText("textField1");
        txtMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMoneyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMoney)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(lblQuantity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity)
                    .addComponent(lblMoney)
                    .addComponent(txtMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMoneyActionPerformed
@Override
protected void paintComponent(Graphics g) {
    super.paintComponent(g);
    Graphics2D g2 = (Graphics2D) g.create();
    g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

    g2.setColor(getBackground());
    g2.fillRoundRect(0, 0, getWidth(), getHeight(), 5, 5); 

    g2.setColor(new Color(100, 100, 100)); 
    g2.setStroke(new BasicStroke(1)); 
    g2.drawRoundRect(1, 1, getWidth() - 3, getHeight() - 3, 5, 5);

    g2.dispose();
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel lblMoney;
    private JLabel lblQuantity;
    private TextField txtMoney;
    // End of variables declaration//GEN-END:variables
}
