/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.shift;

import iuh.fit.se.group1.ui.component.custom.AvatarLabel;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/**
 *
 * @author Administrator
 */
public class ShiftProfile extends javax.swing.JPanel implements MouseListener{
    private boolean isSelect = false;
    private Color defaultTextColor = Color.BLACK;
    private Color selectedTextColor = Color.WHITE;
    private Color defaultBackground = Color.WHITE;
    private Color selectedBackground = new Color(0, 120, 215);
    private Color hoverBackground = new Color(245, 245, 245);
    @Override
    public void mouseClicked(MouseEvent e) {
        rdoSelect.setSelected(!rdoSelect.isSelected());
        isSelect = rdoSelect.isSelected();
        
        updateBackground();
    }

    @Override
    public void mousePressed(MouseEvent e) {
         // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        if (!isSelect) {
            pnlInforEmployee.setBackground(hoverBackground);
        }
    }

    @Override
    public void mouseExited(MouseEvent e) {
        updateBackground();
    }
    /**
     * Creates new form ShiftProfile
     */
    public ShiftProfile() {
        initComponents();
        setPreferredSize(new Dimension(290, getPreferredSize().height));
        rdoSelect.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 24));
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
        String currentCode = lblCode.getText();
        if (!currentCode.startsWith("Mã nhân viên:")) {
            lblCode.setText("Mã nhân viên: " + currentCode);
        }
        rdoSelect.addActionListener(e -> {
            isSelect = rdoSelect.isSelected();
            updateBackground();
        });
    }
    public void updateEmployeeCodeLabel(String code) {
        lblCode.setText("Mã nhân viên: " + code);
    }

    public AvatarLabel getAvatarLabel() {
        return avatarLabel;
    }

    public void setAvatarLabel(AvatarLabel avatarLabel) {
        this.avatarLabel = avatarLabel;
    }

    public JRadioButton getjRadioButton2() {
        return rdoSelect;
    }

    public void setjRadioButton2(JRadioButton jRadioButton2) {
        this.rdoSelect = jRadioButton2;
    }

    public boolean isSelected() {
        return rdoSelect.isSelected();
    }

    public JLabel getLblCode() {
        return lblCode;
    }

    public void setLblCode(JLabel lblCode) {
        this.lblCode = lblCode;
    }

    public JLabel getLblName() {
        return lblName;
    }

    public void setLblName(JLabel lblName) {
        this.lblName = lblName;
    }
    public void setIsSelect(boolean isSelect) {
        this.isSelect = isSelect;
    }
    public void updateBackground() {
        boolean selected = rdoSelect.isSelected() || isSelect;
        pnlInforEmployee.setBackground(selected ? selectedBackground : defaultBackground);
        lblName.setForeground(selected ? selectedTextColor : defaultTextColor);
        lblCode.setForeground(selected ? selectedTextColor : defaultTextColor);
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInforEmployee = new javax.swing.JPanel();
        lblName = new JLabel();
        lblCode = new JLabel();
        avatarLabel = new AvatarLabel();
        rdoSelect = new JRadioButton();

        setBackground(new Color(255, 255, 255));

        pnlInforEmployee.setBackground(new Color(255, 255, 255));

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblName.setText("Nguyễn Chí Tâm");

        lblCode.setText("NV732221213");

        javax.swing.GroupLayout pnlInforEmployeeLayout = new javax.swing.GroupLayout(pnlInforEmployee);
        pnlInforEmployee.setLayout(pnlInforEmployeeLayout);
        pnlInforEmployeeLayout.setHorizontalGroup(
            pnlInforEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInforEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(pnlInforEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(lblCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdoSelect)
                .addGap(11, 11, 11))
        );
        pnlInforEmployeeLayout.setVerticalGroup(
            pnlInforEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInforEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInforEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlInforEmployeeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(avatarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlInforEmployeeLayout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCode)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInforEmployeeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoSelect)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlInforEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlInforEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private AvatarLabel avatarLabel;
    private JLabel lblCode;
    private JLabel lblName;
    private javax.swing.JPanel pnlInforEmployee;
    private JRadioButton rdoSelect;
    // End of variables declaration//GEN-END:variables
}
