/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.booking;

import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

/**
 *
 * @author THIS PC
 */
public class AddRoomPanel extends JPanel {

    private int borderRadius = 5;
    private Color backgroundColor = new Color(131, 176, 212);
    
    /**
     * Creates new form AddRoomPanel
     */
    public AddRoomPanel() {
        initComponents();
        setOpaque(false);
        btnAddRoom.setIcon(FontIcon.of(FontAwesomeSolid.PLUS_CIRCLE, 20, btnAddRoom.getForeground()), SwingConstants.RIGHT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddRoom = new iuh.fit.se.group1.ui.component.custom.Button();

        setBackground(new Color(255, 255, 255));

        btnAddRoom.setBackground(new Color(255, 255, 255));
        btnAddRoom.setForeground(new Color(77, 134, 168));
        btnAddRoom.setText("Thêm phòng");
        btnAddRoom.setFont(new Font("Segoe UI", 1, 12)); // NOI18N

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addComponent(btnAddRoom, GroupLayout.PREFERRED_SIZE, 178, GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddRoom, GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        int arc = borderRadius;
        int w = getWidth();
        int h = getHeight();

        // Vẽ nền bo góc
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, w - 1, h - 1, arc, arc);

        // Vẽ viền nét đứt
        float dash1[] = {8.0f, 8.0f}; // độ dài nét và khoảng cách
        BasicStroke dashed = new BasicStroke(
                2f, // độ dày
                BasicStroke.CAP_BUTT,
                BasicStroke.JOIN_ROUND,
                10.0f, dash1, 0.0f);
        g2.setStroke(dashed);
        g2.setColor(backgroundColor);
        g2.drawRoundRect(1, 1, w - 3, h - 3, arc, arc);

        g2.dispose();
        super.paintComponent(g);
    }

    public void addAction (ActionListener ac) {
        btnAddRoom.addActionListener(ac);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private iuh.fit.se.group1.ui.component.custom.Button btnAddRoom;
    // End of variables declaration//GEN-END:variables
}
