/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.booking;

import com.raven.datechooser.DateChooser;
import iuh.fit.se.group1.ui.component.custom.Combobox;
import iuh.fit.se.group1.ui.component.custom.TextField;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

/**
 *
 * @author THIS PC
 */
public class InfoCustomerPanel extends JPanel {
    
    private int borderRadius = 8;

    private DateChooser dateChooser;

    /**
     * Creates new form InfoCustomerPanel
     */
    public InfoCustomerPanel() {
        initComponents();
        setOpaque(false);
        lblTitle.setIcon(FontIcon.of(FontAwesomeSolid.USER, 20, lblTitle.getForeground()));
        dateChooser = new DateChooser();
        dateChooser.toDay();
        dateChooser.setTextRefernce(txtDob);
        cboGender.addItem("Nam");
        cboGender.addItem("Nữ");
        cboGender.setBackground(new Color(240, 248, 255));
        cboGender.setForeground(new Color(51, 51, 51));
        cboGender.setFont(new Font("Segoe UI", Font.PLAIN, 12));

    }

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        int offset = 2;            // độ lệch bóng
        Color shadowColor = new Color(0, 0, 0, 10); // màu bóng (đen mờ)

        int width = getWidth();
        int height = getHeight();

        // Vẽ bóng (vẽ sau, lệch nhẹ xuống phải)
        g2.setColor(shadowColor);
        g2.fillRoundRect(offset, offset, width - 1, height - 1, borderRadius, borderRadius);

        // Vẽ nền panel thật (che bóng phía trên)
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, width - offset - 1, height - offset - 1, borderRadius, borderRadius);

        g2.dispose();
        super.paintComponent(g);
    }

    public void addActionTxtCitizenId(ActionListener actionListener) {
        txtCitizen.addActionListener(actionListener);
    }

    public Combobox getCboGender() {
        return cboGender;
    }

    public void setCboGender(Combobox cboGender) {
        this.cboGender = cboGender;
    }

    public TextField getTxtCustomerName() {
        return txtCustomerName;
    }

    public void setTxtCustomerName(TextField txtTCustomerName) {
        this.txtCustomerName = txtTCustomerName;
    }

    public TextField getTxtPhoneNumber() {
        return txtPhoneNumber;
    }

    public void setTxtPhoneNumber(TextField txtPhoneNumber) {
        this.txtPhoneNumber = txtPhoneNumber;
    }

    public TextField getTxtEmail() {
        return txtEmail;
    }

    public void setTxtEmail(TextField txtEmail) {
        this.txtEmail = txtEmail;
    }

    public TextField getTxtDob() {
        return txtDob;
    }

    public void setTxtDob(TextField txtDob) {
        this.txtDob = txtDob;
    }

    public TextField getTxtCitizen() {
        return txtCitizen;
    }

    public void setTxtCitizen(TextField txtCitizen) {
        this.txtCitizen = txtCitizen;
    }

    public JSeparator getSpn() {
        return spn;
    }

    public void setSpn(JSeparator spn) {
        this.spn = spn;
    }

    public DateChooser getDateChooser() {
        return dateChooser;
    }

    public void setDateChooser(DateChooser dateChooser) {
        this.dateChooser = dateChooser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new JLabel();
        spn = new JSeparator();
        lblCitizen = new JLabel();
        txtCitizen = new TextField();
        lblCustomerName = new JLabel();
        txtCustomerName = new TextField();
        lblPhoneNumber = new JLabel();
        txtPhoneNumber = new TextField();
        lblDob = new JLabel();
        txtDob = new TextField();
        lblGender = new JLabel();
        lblEmail = new JLabel();
        txtEmail = new TextField();
        cboGender = new Combobox();
        cbDeposit = new JCheckBox();
        cbReserve = new JCheckBox();

        setBackground(new Color(255, 255, 255));

        lblTitle.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lblTitle.setForeground(new Color(131, 176, 211));
        lblTitle.setText("Khách hàng");
        lblTitle.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));

        spn.setBackground(new Color(255, 255, 51));
        spn.setForeground(new Color(217, 217, 217));
        spn.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 10));

        lblCitizen.setFont(new Font("Segoe UI", 1, 10)); // NOI18N
        lblCitizen.setText("CCCD:");

        txtCitizen.setBorderColor(new Color(105, 105, 105));
        txtCitizen.setBorderRadius(3);

        lblCustomerName.setFont(new Font("Segoe UI", 1, 10)); // NOI18N
        lblCustomerName.setText("Tên khách hàng:");

        txtCustomerName.setBorderColor(new Color(105, 105, 105));
        txtCustomerName.setBorderRadius(3);

        lblPhoneNumber.setFont(new Font("Segoe UI", 1, 10)); // NOI18N
        lblPhoneNumber.setText("Số điện thoại:");

        txtPhoneNumber.setBorderColor(new Color(105, 105, 105));
        txtPhoneNumber.setBorderRadius(3);
        txtPhoneNumber.addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });

        lblDob.setFont(new Font("Segoe UI", 1, 10)); // NOI18N
        lblDob.setText("Ngày sinh:");

        txtDob.setBorderColor(new Color(105, 105, 105));
        txtDob.setBorderRadius(3);

        lblGender.setFont(new Font("Segoe UI", 1, 10)); // NOI18N
        lblGender.setText("Giới tính:");

        lblEmail.setFont(new Font("Segoe UI", 1, 10)); // NOI18N
        lblEmail.setText("Email: ");

        txtEmail.setBorderColor(new Color(105, 105, 105));
        txtEmail.setBorderRadius(3);

        cbDeposit.setFont(new Font("Segoe UI", 1, 10)); // NOI18N
        cbDeposit.setText("Tiền cọc");

        cbReserve.setText("Đặt trước phòng");
        cbReserve.addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbReserveActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, GroupLayout.PREFERRED_SIZE, 186, GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(spn, GroupLayout.PREFERRED_SIZE, 541, GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCitizen, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCitizen, GroupLayout.PREFERRED_SIZE, 197, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCustomerName, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCustomerName, GroupLayout.PREFERRED_SIZE, 192, GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEmail)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmail, GroupLayout.PREFERRED_SIZE, 192, GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(cbDeposit, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(cbReserve))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPhoneNumber)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPhoneNumber, GroupLayout.PREFERRED_SIZE, 103, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDob)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDob, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGender, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboGender, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spn, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lblCustomerName, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCitizen, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCitizen, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCustomerName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumber, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNumber, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDob, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDob, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGender, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboGender, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEmail, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbDeposit)
                        .addComponent(cbReserve)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void cbReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbReserveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbReserveActionPerformed

    public JCheckBox getCbReserve() {
        return cbReserve;
    }

    public void setCbReserve(JCheckBox cbReserve) {
        this.cbReserve = cbReserve;
    }

    public JCheckBox getCbDeposit() {
        return cbDeposit;
    }

    public void setCbDeposit(JCheckBox cbDeposit) {
        this.cbDeposit = cbDeposit;
    }

    public void clearForm(){
        txtCitizen.setText("");
        txtCustomerName.setText("");
        txtPhoneNumber.setText("");
        txtDob.setText("");
        txtEmail.setText("");
        cboGender.setSelectedIndex(-1);
        cbDeposit.setSelected(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JCheckBox cbDeposit;
    private JCheckBox cbReserve;
    private Combobox cboGender;
    private JLabel lblCitizen;
    private JLabel lblCustomerName;
    private JLabel lblDob;
    private JLabel lblEmail;
    private JLabel lblGender;
    private JLabel lblPhoneNumber;
    private JLabel lblTitle;
    private JSeparator spn;
    private TextField txtCitizen;
    private TextField txtCustomerName;
    private TextField txtDob;
    private TextField txtEmail;
    private TextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
