/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.booking;

import javax.swing.*;
import java.awt.*;
import java.util.Map;

/**
 *
 * @author THIS PC
 */
public class InfoAmenityPanel extends JPanel {
    
    private String amenityId;
    private int borderRadius = 4;
    /**
     * Creates new form InfoAmenityPanel
     */
    public InfoAmenityPanel() {
        initComponents();
        setOpaque(false);
        setBackground(new Color(233,233,233)); // màu nền nhẹ như hình
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numberSpinner = new NumberSpinner();
        lblName = new JLabel();
        lblPrice = new JLabel();

        setBackground(new Color(223, 228, 231));

        lblName.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lblName.setForeground(new Color(77, 134, 168));
        lblName.setText("Dịch vụ thêm chăn mềm");

        lblPrice.setFont(new Font("Segoe UI", 1, 10)); // NOI18N
        lblPrice.setForeground(new Color(255, 108, 3));
        lblPrice.setText("150k");

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, GroupLayout.PREFERRED_SIZE, 201, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(numberSpinner, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblName)
                .addGap(2, 2, 2)
                .addComponent(lblPrice)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(numberSpinner, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        int offset = 2;            // độ lệch bóng
        Color shadowColor = new Color(0, 0, 0, 10); // màu bóng (đen mờ)

        int width = getWidth();
        int height = getHeight();

        // Vẽ bóng (vẽ sau, lệch nhẹ xuống phải)
        g2.setColor(shadowColor);
        g2.fillRoundRect(offset, offset, width - 1, height - 1, borderRadius, borderRadius);

        // Vẽ nền panel thật (che bóng phía trên)
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, width - offset - 1, height - offset - 1, borderRadius, borderRadius);

        g2.dispose();
        super.paintComponent(g);
    }

    public NumberSpinner getNumberSpinner() {
        return numberSpinner;
    }

    
    public Map<String ,String> getValue (){
        return Map.of("amenityId", amenityId, "quantity", String.valueOf(numberSpinner.getValue()), "price", lblPrice.getText());
    }

    public void setNumberSpinner(NumberSpinner numberSpinner) {
        this.numberSpinner = numberSpinner;
    }


    public String getAmenityId() {
        return amenityId;
    }

    public void setAmenityId(String amenityId) {
        this.amenityId = amenityId;
    }

    public JLabel getLblName() {
        return lblName;
    }

    public void setLblName(JLabel lblName) {
        this.lblName = lblName;
    }

    public JLabel getLblPrice() {
        return lblPrice;
    }

    public void setLblPrice(JLabel lblPrice) {
        this.lblPrice = lblPrice;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel lblName;
    private JLabel lblPrice;
    private NumberSpinner numberSpinner;
    // End of variables declaration//GEN-END:variables
}
