/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.payment;

import iuh.fit.se.group1.ui.component.custom.Button;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;
import raven.glasspanepopup.GlassPanePopup;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Administrator
 */
public class TransferPaymentModal extends JPanel {

    public JLabel getLblQrCode() {
        return lblQrCode;
    }

    public void setLblQrCode(JLabel lblQrCode) {
        this.lblQrCode = lblQrCode;
    }

    
    public Button getBtnCheck() {
        return btnCheck;
    }

    public void setBtnCheck(Button btnCheck) {
        this.btnCheck = btnCheck;
    }

    public Button getBtnExit() {
        return btnExit;
    }

    public void setBtnExit(Button btnExit) {
        this.btnExit = btnExit;
    }

    public JLabel getLblTitle() {
        return lblTitle;
    }

    public void setLblTitle(JLabel lblTitle) {
        this.lblTitle = lblTitle;
    }

    public JLabel getLblTotaPrice() {
        return lblTotaPrice;
    }

    public void setLblTotaPrice(JLabel lblTotaPrice) {
        this.lblTotaPrice = lblTotaPrice;
    }

    public JPanel getPnlQRCode() {
        return pnlQRCode;
    }



    public void setPnlQRCode(JPanel pnlQRCode) {
        this.pnlQRCode = pnlQRCode;
    }

    
    /**
     * Creates new form TransferPaymentModal
     */
    public TransferPaymentModal() {
        initComponents();
        btnExit.setIcon(FontIcon.of(FontAwesomeSolid.TIMES_CIRCLE, 20));
        btnExit.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        btnExit.setText("");
        btnExit.setOpaque(false);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new JLabel();
        btnExit = new Button();
        pnlQRCode = new JPanel();
        lblQrCode = new JLabel();
        lblTotaPrice = new JLabel();
        btnCheck = new Button();

        setBackground(new java.awt.Color(129, 129, 129));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(SwingConstants.CENTER);
        lblTitle.setText("Thanh toán chuyển khoản");

        btnExit.setBackground(new java.awt.Color(129, 129, 129));
        btnExit.setText(" ");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        pnlQRCode.setBackground(new java.awt.Color(255, 255, 255));
        pnlQRCode.setForeground(new java.awt.Color(255, 255, 255));

        GroupLayout pnlQRCodeLayout = new GroupLayout(pnlQRCode);
        pnlQRCode.setLayout(pnlQRCodeLayout);
        pnlQRCodeLayout.setHorizontalGroup(
            pnlQRCodeLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(lblQrCode, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlQRCodeLayout.setVerticalGroup(
            pnlQRCodeLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(lblQrCode, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        lblTotaPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotaPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblTotaPrice.setHorizontalAlignment(SwingConstants.CENTER);
        lblTotaPrice.setText("Tổng tiền: 1234");

        btnCheck.setBackground(new java.awt.Color(249, 115, 22));
        btnCheck.setForeground(new java.awt.Color(255, 255, 255));
        btnCheck.setText("Kiểm tra");
        btnCheck.setBorderRadius(5);
        btnCheck.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTitle, GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(btnCheck, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlQRCode, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotaPrice, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addComponent(btnExit, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnExit, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlQRCode, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotaPrice, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCheck, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        GlassPanePopup.closePopupLast();
    }//GEN-LAST:event_btnExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Button btnCheck;
    private Button btnExit;
    private JLabel lblQrCode;
    private JLabel lblTitle;
    private JLabel lblTotaPrice;
    private JPanel pnlQRCode;
    // End of variables declaration//GEN-END:variables
}
